=== DevMystogan/Datapack/gameserver/data/items/items.xsd
<?xml version="1.1" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://l2j.org"
           xmlns="http://l2j.org"
           elementFormDefault="qualified">

    <xs:include schemaLocation="../xsd/common.xsd"/>

    <xs:element name="itemGroup" type="AbstractItem" abstract="true" />
    <xs:element name="weapon" type="Weapon" substitutionGroup="itemGroup"/>
    <xs:element name="armor" type="Armor" substitutionGroup="itemGroup"/>
    <xs:element name="item" type="Item" substitutionGroup="itemGroup"/>

    <xs:element name="list">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="itemGroup" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="AbstractItem" abstract="true">
        <xs:sequence>
            <xs:element name="restriction" type="Restriction"/>
            <xs:element name="condition" minOccurs="0" type="condType"/>
            <xs:element name="skills" minOccurs="0" type="SkillsType"/>
        </xs:sequence>
        <xs:attribute name="id" use="required" type="xs:positiveInteger"/>
        <xs:attribute name="name" type="xs:normalizedString" use="required"/>
        <xs:attribute name="icon" type="xs:token"/>
        <xs:attribute name="display-id" type="xs:int" default="0"/>
    </xs:complexType>

    <xs:complexType name="Attributes" abstract="true">
        <xs:attribute name="weight" type="xs:int" default="0"/>
        <xs:attribute name="price" type="xs:int" default="0"/>
        <xs:attribute name="commission-type" type="CommissionType" default="OTHER_ITEM"/>
        <xs:attribute name="reuse-delay" type="xs:long" />
    </xs:complexType>

    <xs:complexType name="WeaponAttributes">
        <xs:complexContent>
            <xs:extension base="Attributes">
                <xs:attribute name="enchant-enabled" type="xs:boolean" default="true"/>
                <xs:attribute name="commission-type" type="CommissionType" default="OTHER_WEAPON"/>
                <xs:attribute name="change-weapon" type="xs:int" default="0"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="ItemAttributes">
        <xs:complexContent>
            <xs:extension base="Attributes">
                <xs:attribute name="immediate-effect" type="xs:boolean" default="false"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="ArmorAttributes">
        <xs:complexContent>
            <xs:extension base="Attributes">
                <xs:attribute name="enchant-enabled" type="xs:boolean" default="true"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Restriction">
        <xs:attribute name="stackable" type="xs:boolean" default="false"/>
        <xs:attribute name="sellable" type="xs:boolean" default="true"/>
        <xs:attribute name="dropable" type="xs:boolean" default="true"/>
        <xs:attribute name="destroyable" type="xs:boolean" default="true"/>
        <xs:attribute name="tradable" type="xs:boolean" default="true"/>
        <xs:attribute name="depositable" type="xs:boolean" default="true"/>
        <xs:attribute name="clan-depositable" type="xs:boolean" default="true"/>
        <xs:attribute name="freightable" type="xs:boolean" default="false"/>
        <xs:attribute name="commissionable" type="xs:boolean" default="true"/>
        <xs:attribute name="mailable" type="xs:boolean" default="true"/>
        <xs:attribute name="olympiad-restricted" type="xs:boolean" default="false"/>
        <xs:attribute name="coc-restricted" type="xs:boolean" default="false"/>
    </xs:complexType>

    <xs:complexType name="Weapon">
        <xs:complexContent>
            <xs:extension base="AbstractItem">
                <xs:sequence>
                    <xs:element name="attributes" type="WeaponAttributes"/>
                    <xs:element name="crystal" type="ItemCrystal"/>
                    <xs:element name="damage" type="WeaponDamage"/>
                    <xs:element name="consume" type="WeaponConsume"/>
                    <xs:element name="stats" minOccurs="0" type="ItemStats"/>
                </xs:sequence>
                <xs:attribute name="type" type="WeaponType" use="required"/>
                <xs:attribute name="body-part" type="WeaponBodyPart"/>
                <xs:attribute name="is-magic" type="xs:boolean" default="false"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="WeaponConsume">
        <xs:attribute name="soulshots" type="xs:int" default="1"/>
        <xs:attribute name="spiritshots" type="xs:int" default="1"/>
        <xs:attribute name="mana" type="xs:int" default="0"/>
    </xs:complexType>

    <xs:complexType name="WeaponDamage">
        <xs:attribute name="radius" type="xs:int"/>
        <xs:attribute name="angle" type="xs:int"/>
    </xs:complexType>

    <xs:complexType name="Armor">
        <xs:complexContent>
            <xs:extension base="AbstractItem">
                <xs:sequence>
                    <xs:element name="attributes" type="ArmorAttributes"/>
                    <xs:element name="crystal" type="ItemCrystal"/>
                    <xs:element name="stats" minOccurs="0" type="ItemStats"/>
                </xs:sequence>
                <xs:attribute name="type" type="ArmorType" use="required"/>
                <xs:attribute name="body-part" type="ArmorBodyPart" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="ItemCrystal">
        <xs:attribute name="type" type="ItemGrade" default="NONE"/>
        <xs:attribute name="count" type="xs:int" default="0"/>
    </xs:complexType>

    <xs:complexType name="Item">
        <xs:complexContent>
            <xs:extension base="AbstractItem">
                <xs:sequence>
                    <xs:element name="attributes" type="ItemAttributes"/>
                    <xs:element name="action"/>
                </xs:sequence>
                <xs:attribute name="type" type="EtcItemType" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="SkillsType">
        <xs:sequence>
            <xs:element name="skill" type="SkillType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="unequipSkillsType">
        <xs:sequence>
            <xs:element name="skill" type="SkillType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="capsuledItemsType">
        <xs:sequence>
            <xs:element name="item" type="capsuledItemType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="SkillType">
        <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
        <xs:attribute name="level" type="xs:positiveInteger" use="required"/>
        <xs:attribute name="type" default="NORMAL">
            <xs:simpleType>
                <xs:restriction base="xs:token">
                    <xs:enumeration value="NORMAL"/>
                    <xs:enumeration value="ON_ENCHANT"/>
                    <xs:enumeration value="ON_EQUIP"/>
                    <xs:enumeration value="ON_UNEQUIP"/>
                    <xs:enumeration value="ON_CRITICAL_SKILL"/>
                    <xs:enumeration value="ON_MAGIC_SKILL"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="chance" type="xs:positiveInteger" default="100"/>
        <xs:attribute name="value" type="xs:positiveInteger" default="0"/>
    </xs:complexType>

    <xs:complexType name="capsuledItemType">
        <xs:attribute name="id" type="xs:positiveInteger"/>
        <xs:attribute name="min" type="xs:positiveInteger"/>
        <xs:attribute name="max" type="xs:positiveInteger"/>
        <xs:attribute name="chance" type="xs:double"/>
        <xs:attribute name="minEnchant" type="xs:positiveInteger" use="optional"/>
        <xs:attribute name="maxEnchant" type="xs:positiveInteger" use="optional"/>
    </xs:complexType>

    <xs:complexType name="createItemType">
        <xs:attribute name="id" type="xs:positiveInteger"/>
        <xs:attribute name="count" type="xs:positiveInteger"/>
        <xs:attribute name="chance" type="xs:double"/>
    </xs:complexType>

    <xs:complexType name="setType">
        <xs:attribute name="name" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:token">
                    <xs:enumeration value="armor_type"/>
                    <xs:enumeration value="auto_destroy_time"/>
                    <xs:enumeration value="blessed"/>
                    <xs:enumeration value="bodypart"/>
                    <xs:enumeration value="capsuled_items"/>
                    <xs:enumeration value="change_weaponId"/>
                    <xs:enumeration value="crystal_count"/>
                    <xs:enumeration value="crystal_type"/>
                    <xs:enumeration value="damage_range"/>
                    <xs:enumeration value="default_action"/>
                    <xs:enumeration value="enchant_enabled"/>
                    <xs:enumeration value="equip_reuse_delay"/>
                    <xs:enumeration value="ex_immediate_effect"/>
                    <xs:enumeration value="extractableCountMin"/>
                    <xs:enumeration value="extractableCountMax"/>
                    <xs:enumeration value="etcitem_type"/>
                    <xs:enumeration value="for_npc"/>
                    <xs:enumeration value="handler"/>
                    <xs:enumeration value="immediate_effect"/>
                    <xs:enumeration value="is_magic_weapon"/>
                    <xs:enumeration value="is_questitem"/>
                    <xs:enumeration value="is_infinite"/>
                    <xs:enumeration value="isAttackWeapon"/>
                    <xs:enumeration value="allow_self_resurrection"/>
                    <xs:enumeration value="mp_consume"/>
                    <xs:enumeration value="price"/>
                    <xs:enumeration value="reduced_mp_consume"/>
                    <xs:enumeration value="reduced_soulshot"/>
                    <xs:enumeration value="reuse_delay"/>
                    <xs:enumeration value="shared_reuse_group"/>
                    <xs:enumeration value="soulshots"/>
                    <xs:enumeration value="spiritshots"/>
                    <xs:enumeration value="time"/>
                    <xs:enumeration value="useWeaponSkillsOnly"/>
                    <xs:enumeration value="weapon_type"/>
                    <xs:enumeration value="weight"/>
                    <xs:enumeration value="commissionItemType"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="val" type="xs:token" use="required"/>
    </xs:complexType>
    <xs:complexType name="playerType">
        <xs:attribute name="castle">
            <xs:simpleType>
                <xs:restriction base="xs:integer">
                    <xs:minInclusive value="-1"/>
                    <xs:maxInclusive value="9"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="isOnSide" use="optional">
            <xs:simpleType>
                <xs:restriction base="xs:token">
                    <xs:enumeration value="NEUTRAL"/>
                    <xs:enumeration value="LIGHT"/>
                    <xs:enumeration value="DARK"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="isClanLeader" type="xs:boolean"/>
        <xs:attribute name="clanHall" type="xs:normalizedString"/>
        <xs:attribute name="class_id_restriction" type="xs:normalizedString"/>
        <xs:attribute name="cloakStatus" type="xs:boolean"/>
        <xs:attribute name="isHero" type="xs:boolean"/>
        <xs:attribute name="isPvpFlagged" type="xs:boolean"/>
        <xs:attribute name="insideZoneId" type="xs:normalizedString"/>
        <xs:attribute name="level">
            <xs:simpleType>
                <xs:restriction base="xs:positiveInteger">
                    <xs:minInclusive value="1"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="pledgeClass">
            <xs:simpleType>
                <xs:restriction base="xs:integer">
                    <xs:minInclusive value="-1"/>
                    <xs:maxInclusive value="11"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="levelRange" type="xs:token"/>
        <xs:attribute name="races" type="xs:token"/>
        <xs:attribute name="sex" type="xs:byte" use="optional"/>
        <xs:attribute name="fort" type="xs:integer"/>
        <xs:attribute name="chaotic" type="xs:boolean"/>
        <xs:attribute name="subclass" type="xs:boolean"/>
        <xs:attribute name="SiegeZone" type="xs:positiveInteger"/>
        <xs:attribute name="flyMounted" type="xs:boolean"/>
        <xs:attribute name="instanceId" type="xs:normalizedString"/>
        <xs:attribute name="categoryType" type="xs:normalizedString"/>
        <xs:attribute name="pkCount" type="xs:int"/>
        <xs:attribute name="vehicleMounted" type="xs:boolean"/>
        <xs:attribute name="MinimumVitalityPoints" type="xs:int"/>
    </xs:complexType>
    <xs:complexType name="andType">
        <xs:choice maxOccurs="unbounded" minOccurs="0">
            <xs:element name="using" type="usingType"/>
            <xs:element name="player" type="playerType"/>
            <xs:element name="target" type="targetType"/>
            <xs:element name="not" type="notType"/>
            <xs:element name="game" type="gameType"/>
            <xs:element name="or" minOccurs="0" type="andType"/>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="gameType">
        <xs:attribute type="xs:string" name="night"/>
    </xs:complexType>
    <xs:complexType name="notType">
        <xs:sequence>
            <xs:element name="using" minOccurs="0" type="usingType"/>
            <xs:element name="player" minOccurs="0" type="playerType"/>
            <xs:element name="target" minOccurs="0" type="targetType"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="usingType">
        <xs:attribute type="xs:string" name="kind" use="optional"/>
        <xs:attribute type="xs:string" name="slot" use="optional"/>
        <xs:attribute type="xs:string" name="weaponChange" use="optional"/>
    </xs:complexType>
    <xs:complexType name="targetType">
        <xs:attribute name="levelRange" type="xs:token"/>
        <xs:attribute name="categoryType" type="xs:normalizedString"/>
    </xs:complexType>
    <xs:complexType name="enchantType">
        <xs:attribute name="order" type="xs:byte" use="optional"/>
        <xs:attribute name="stat" use="required" type="Stat"/>
        <xs:attribute name="val" type="xs:integer" fixed="0" use="required"/>
    </xs:complexType>
    <xs:complexType name="condType">
        <xs:choice maxOccurs="unbounded" minOccurs="0">
            <xs:element name="using" type="usingType"/>
            <xs:element name="and" type="andType"/>
            <xs:element name="not" type="notType"/>
            <xs:element name="player" type="playerType"/>
            <xs:element name="target" type="targetType"/>
        </xs:choice>
        <xs:attribute type="xs:short" name="msgId" use="optional"/>
        <xs:attribute type="xs:byte" name="addName" use="optional"/>
        <xs:attribute type="xs:string" name="msg" use="optional"/>
    </xs:complexType>


    <xs:complexType name="ItemStats">
        <xs:sequence>
            <xs:element name="stat" type="ItemStat" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ItemStat">
        <xs:attribute name="type" type="Stat"/>
        <xs:attribute name="value" type="xs:float"/>
    </xs:complexType>

    <xs:simpleType name="CommissionType">
        <xs:restriction base="xs:token">
            <xs:enumeration value="ONE_HAND_SWORD"/>
            <xs:enumeration value="ONE_HAND_MAGIC_SWORD"/>
            <xs:enumeration value="DAGGER"/>
            <xs:enumeration value="RAPIER"/>
            <xs:enumeration value="TWO_HAND_SWORD"/>
            <xs:enumeration value="ANCIENT_SWORD"/>
            <xs:enumeration value="DUALSWORD"/>
            <xs:enumeration value="DUAL_DAGGER"/>
            <xs:enumeration value="BLUNT_WEAPON"/>
            <xs:enumeration value="ONE_HAND_MAGIC_BLUNT_WEAPON"/>
            <xs:enumeration value="TWO_HAND_BLUNT_WEAPON"/>
            <xs:enumeration value="TWO_HAND_MAGIC_BLUNT_WEAPON"/>
            <xs:enumeration value="DUAL_BLUNT_WEAPON"/>
            <xs:enumeration value="BOW"/>
            <xs:enumeration value="CROSSBOW"/>
            <xs:enumeration value="FIST_WEAPON"/>
            <xs:enumeration value="SPEAR"/>
            <xs:enumeration value="OTHER_WEAPON"/>
            <xs:enumeration value="HELMET"/>
            <xs:enumeration value="ARMOR_TOP"/>
            <xs:enumeration value="ARMOR_PANTS"/>
            <xs:enumeration value="FULL_BODY"/>
            <xs:enumeration value="GLOVES"/>
            <xs:enumeration value="FEET"/>
            <xs:enumeration value="SHIELD"/>
            <xs:enumeration value="SIGIL"/>
            <xs:enumeration value="UNDERWEAR"/>
            <xs:enumeration value="CLOAK"/>
            <xs:enumeration value="RING"/>
            <xs:enumeration value="EARRING"/>
            <xs:enumeration value="NECKLACE"/>
            <xs:enumeration value="BELT"/>
            <xs:enumeration value="BRACELET"/>
            <xs:enumeration value="HAIR_ACCESSORY"/>
            <xs:enumeration value="POTION"/>
            <xs:enumeration value="SCROLL_ENCHANT_WEAPON"/>
            <xs:enumeration value="SCROLL_ENCHANT_ARMOR"/>
            <xs:enumeration value="SCROLL_OTHER"/>
            <xs:enumeration value="SOULSHOT"/>
            <xs:enumeration value="SPIRITSHOT"/>
            <xs:enumeration value="PET_EQUIPMENT"/>
            <xs:enumeration value="PET_SUPPLIES"/>
            <xs:enumeration value="CRYSTAL"/>
            <xs:enumeration value="RECIPE"/>
            <xs:enumeration value="MAJOR_CRAFTING_INGREDIENTS"/>
            <xs:enumeration value="LIFE_STONE"/>
            <xs:enumeration value="SOUL_CRYSTAL"/>
            <xs:enumeration value="ATTRIBUTE_STONE"/>
            <xs:enumeration value="WEAPON_ENCHANT_STONE"/>
            <xs:enumeration value="ARMOR_ENCHANT_STONE"/>
            <xs:enumeration value="SPELLBOOK"/>
            <xs:enumeration value="GEMSTONE"/>
            <xs:enumeration value="POUCH"/>
            <xs:enumeration value="PIN"/>
            <xs:enumeration value="MAGIC_RUNE_CLIP"/>
            <xs:enumeration value="MAGIC_ORNAMENT"/>
            <xs:enumeration value="DYES"/>
            <xs:enumeration value="OTHER_ITEM"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== DevMystogan/Datapack/gameserver/data/items/39700-39799.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://l2j.org" xsi:schemaLocation="http://l2j.org items.xsd">
	<weapon id="39719" name="Monster only_Crook Staff" type="SPEAR" body-part="TWO_HAND" icon="icon.wp_fishing4">
	<!-- A monster-only weapon. -->
		<restriction freightable="false" destroyable="false" tradable="false" dropable="false" sellable="false" private-sellable="false"/>
		<attributes weight="205" commission-type="OTHER_ITEM" enchant-enabled="false"/>
		<crystal type="D"/>
		<damage radius="40" angle="240"/>
		<consume />
		<stats>
			<stat type="pAtk" value="92.0"/>
			<stat type="mAtk" value="54.0"/>
			<stat type="rCrit" value="8.0"/>
			<stat type="accCombat" value="-3.75"/>
			<stat type="pAtkSpd" value="325.0"/>
			<stat type="randomDamage" value="10.0"/>
			<stat type="pAtkRange" value="80.0"/>
		</stats>
	</weapon>

</list>
