=== DevMystogan/Datapack/gameserver/data/items/items.xsd
<?xml version="1.1" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://l2j.org"
           xmlns="http://l2j.org"
           elementFormDefault="qualified">

    <xs:include schemaLocation="../xsd/common.xsd"/>

    <xs:element name="itemGroup" type="AbstractItem" abstract="true" />
    <xs:element name="weapon" type="Weapon" substitutionGroup="itemGroup"/>
    <xs:element name="armor" type="Armor" substitutionGroup="itemGroup"/>
    <xs:element name="item" type="Item" substitutionGroup="itemGroup"/>

    <xs:element name="list">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="itemGroup" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="AbstractItem" abstract="true">
        <xs:sequence>
            <xs:element name="restriction" type="Restriction"/>
            <xs:element name="condition" minOccurs="0" type="condType"/>
            <xs:element name="skills" minOccurs="0" type="SkillsType"/>
        </xs:sequence>
        <xs:attribute name="id" use="required" type="xs:positiveInteger"/>
        <xs:attribute name="name" type="xs:normalizedString" use="required"/>
        <xs:attribute name="icon" type="xs:token"/>
        <xs:attribute name="display-id" type="xs:int" default="0"/>
    </xs:complexType>

    <xs:complexType name="Attributes" abstract="true">
        <xs:attribute name="weight" type="xs:int" default="0"/>
        <xs:attribute name="price" type="xs:int" default="0"/>
        <xs:attribute name="commission-type" type="CommissionType" default="OTHER_ITEM"/>
        <xs:attribute name="reuse-delay" type="xs:long" />
    </xs:complexType>

    <xs:complexType name="WeaponAttributes">
        <xs:complexContent>
            <xs:extension base="Attributes">
                <xs:attribute name="enchant-enabled" type="xs:boolean" default="true"/>
                <xs:attribute name="commission-type" type="CommissionType" default="OTHER_WEAPON"/>
                <xs:attribute name="change-weapon" type="xs:int" default="0"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="ItemAttributes">
        <xs:complexContent>
            <xs:extension base="Attributes">
                <xs:attribute name="immediate-effect" type="xs:boolean" default="false"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="ArmorAttributes">
        <xs:complexContent>
            <xs:extension base="Attributes">
                <xs:attribute name="enchant-enabled" type="xs:boolean" default="true"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Restriction">
        <xs:attribute name="stackable" type="xs:boolean" default="false"/>
        <xs:attribute name="sellable" type="xs:boolean" default="true"/>
        <xs:attribute name="dropable" type="xs:boolean" default="true"/>
        <xs:attribute name="destroyable" type="xs:boolean" default="true"/>
        <xs:attribute name="tradable" type="xs:boolean" default="true"/>
        <xs:attribute name="depositable" type="xs:boolean" default="true"/>
        <xs:attribute name="clan-depositable" type="xs:boolean" default="true"/>
        <xs:attribute name="freightable" type="xs:boolean" default="false"/>
        <xs:attribute name="commissionable" type="xs:boolean" default="true"/>
        <xs:attribute name="mailable" type="xs:boolean" default="true"/>
        <xs:attribute name="olympiad-restricted" type="xs:boolean" default="false"/>
        <xs:attribute name="coc-restricted" type="xs:boolean" default="false"/>
    </xs:complexType>

    <xs:complexType name="Weapon">
        <xs:complexContent>
            <xs:extension base="AbstractItem">
                <xs:sequence>
                    <xs:element name="attributes" type="WeaponAttributes"/>
                    <xs:element name="crystal" type="ItemCrystal"/>
                    <xs:element name="damage" type="WeaponDamage"/>
                    <xs:element name="consume" type="WeaponConsume"/>
                    <xs:element name="stats" minOccurs="0" type="ItemStats"/>
                </xs:sequence>
                <xs:attribute name="type" type="WeaponType" use="required"/>
                <xs:attribute name="body-part" type="WeaponBodyPart"/>
                <xs:attribute name="is-magic" type="xs:boolean" default="false"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="WeaponConsume">
        <xs:attribute name="soulshots" type="xs:int" default="1"/>
        <xs:attribute name="spiritshots" type="xs:int" default="1"/>
        <xs:attribute name="mana" type="xs:int" default="0"/>
    </xs:complexType>

    <xs:complexType name="WeaponDamage">
        <xs:attribute name="radius" type="xs:int"/>
        <xs:attribute name="angle" type="xs:int"/>
    </xs:complexType>

    <xs:complexType name="Armor">
        <xs:complexContent>
            <xs:extension base="AbstractItem">
                <xs:sequence>
                    <xs:element name="attributes" type="ArmorAttributes"/>
                    <xs:element name="crystal" type="ItemCrystal"/>
                    <xs:element name="stats" minOccurs="0" type="ItemStats"/>
                </xs:sequence>
                <xs:attribute name="type" type="ArmorType" use="required"/>
                <xs:attribute name="body-part" type="ArmorBodyPart" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="ItemCrystal">
        <xs:attribute name="type" type="ItemGrade" default="NONE"/>
        <xs:attribute name="count" type="xs:int" default="0"/>
    </xs:complexType>

    <xs:complexType name="Item">
        <xs:complexContent>
            <xs:extension base="AbstractItem">
                <xs:sequence>
                    <xs:element name="attributes" type="ItemAttributes"/>
                    <xs:element name="action"/>
                </xs:sequence>
                <xs:attribute name="type" type="EtcItemType" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="SkillsType">
        <xs:sequence>
            <xs:element name="skill" type="SkillType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="unequipSkillsType">
        <xs:sequence>
            <xs:element name="skill" type="SkillType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="capsuledItemsType">
        <xs:sequence>
            <xs:element name="item" type="capsuledItemType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="SkillType">
        <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
        <xs:attribute name="level" type="xs:positiveInteger" use="required"/>
        <xs:attribute name="type" default="NORMAL">
            <xs:simpleType>
                <xs:restriction base="xs:token">
                    <xs:enumeration value="NORMAL"/>
                    <xs:enumeration value="ON_ENCHANT"/>
                    <xs:enumeration value="ON_EQUIP"/>
                    <xs:enumeration value="ON_UNEQUIP"/>
                    <xs:enumeration value="ON_CRITICAL_SKILL"/>
                    <xs:enumeration value="ON_MAGIC_SKILL"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="chance" type="xs:positiveInteger" default="100"/>
        <xs:attribute name="value" type="xs:positiveInteger" default="0"/>
    </xs:complexType>

    <xs:complexType name="capsuledItemType">
        <xs:attribute name="id" type="xs:positiveInteger"/>
        <xs:attribute name="min" type="xs:positiveInteger"/>
        <xs:attribute name="max" type="xs:positiveInteger"/>
        <xs:attribute name="chance" type="xs:double"/>
        <xs:attribute name="minEnchant" type="xs:positiveInteger" use="optional"/>
        <xs:attribute name="maxEnchant" type="xs:positiveInteger" use="optional"/>
    </xs:complexType>

    <xs:complexType name="createItemType">
        <xs:attribute name="id" type="xs:positiveInteger"/>
        <xs:attribute name="count" type="xs:positiveInteger"/>
        <xs:attribute name="chance" type="xs:double"/>
    </xs:complexType>

    <xs:complexType name="setType">
        <xs:attribute name="name" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:token">
                    <xs:enumeration value="armor_type"/>
                    <xs:enumeration value="auto_destroy_time"/>
                    <xs:enumeration value="blessed"/>
                    <xs:enumeration value="bodypart"/>
                    <xs:enumeration value="capsuled_items"/>
                    <xs:enumeration value="change_weaponId"/>
                    <xs:enumeration value="crystal_count"/>
                    <xs:enumeration value="crystal_type"/>
                    <xs:enumeration value="damage_range"/>
                    <xs:enumeration value="default_action"/>
                    <xs:enumeration value="enchant_enabled"/>
                    <xs:enumeration value="equip_reuse_delay"/>
                    <xs:enumeration value="ex_immediate_effect"/>
                    <xs:enumeration value="extractableCountMin"/>
                    <xs:enumeration value="extractableCountMax"/>
                    <xs:enumeration value="etcitem_type"/>
                    <xs:enumeration value="for_npc"/>
                    <xs:enumeration value="handler"/>
                    <xs:enumeration value="immediate_effect"/>
                    <xs:enumeration value="is_magic_weapon"/>
                    <xs:enumeration value="is_questitem"/>
                    <xs:enumeration value="is_infinite"/>
                    <xs:enumeration value="isAttackWeapon"/>
                    <xs:enumeration value="allow_self_resurrection"/>
                    <xs:enumeration value="mp_consume"/>
                    <xs:enumeration value="price"/>
                    <xs:enumeration value="reduced_mp_consume"/>
                    <xs:enumeration value="reduced_soulshot"/>
                    <xs:enumeration value="reuse_delay"/>
                    <xs:enumeration value="shared_reuse_group"/>
                    <xs:enumeration value="soulshots"/>
                    <xs:enumeration value="spiritshots"/>
                    <xs:enumeration value="time"/>
                    <xs:enumeration value="useWeaponSkillsOnly"/>
                    <xs:enumeration value="weapon_type"/>
                    <xs:enumeration value="weight"/>
                    <xs:enumeration value="commissionItemType"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="val" type="xs:token" use="required"/>
    </xs:complexType>
    <xs:complexType name="playerType">
        <xs:attribute name="castle">
            <xs:simpleType>
                <xs:restriction base="xs:integer">
                    <xs:minInclusive value="-1"/>
                    <xs:maxInclusive value="9"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="isOnSide" use="optional">
            <xs:simpleType>
                <xs:restriction base="xs:token">
                    <xs:enumeration value="NEUTRAL"/>
                    <xs:enumeration value="LIGHT"/>
                    <xs:enumeration value="DARK"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="isClanLeader" type="xs:boolean"/>
        <xs:attribute name="clanHall" type="xs:normalizedString"/>
        <xs:attribute name="class_id_restriction" type="xs:normalizedString"/>
        <xs:attribute name="cloakStatus" type="xs:boolean"/>
        <xs:attribute name="isHero" type="xs:boolean"/>
        <xs:attribute name="isPvpFlagged" type="xs:boolean"/>
        <xs:attribute name="insideZoneId" type="xs:normalizedString"/>
        <xs:attribute name="level">
            <xs:simpleType>
                <xs:restriction base="xs:positiveInteger">
                    <xs:minInclusive value="1"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="pledgeClass">
            <xs:simpleType>
                <xs:restriction base="xs:integer">
                    <xs:minInclusive value="-1"/>
                    <xs:maxInclusive value="11"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="levelRange" type="xs:token"/>
        <xs:attribute name="races" type="xs:token"/>
        <xs:attribute name="sex" type="xs:byte" use="optional"/>
        <xs:attribute name="fort" type="xs:integer"/>
        <xs:attribute name="chaotic" type="xs:boolean"/>
        <xs:attribute name="subclass" type="xs:boolean"/>
        <xs:attribute name="SiegeZone" type="xs:positiveInteger"/>
        <xs:attribute name="flyMounted" type="xs:boolean"/>
        <xs:attribute name="instanceId" type="xs:normalizedString"/>
        <xs:attribute name="categoryType" type="xs:normalizedString"/>
        <xs:attribute name="pkCount" type="xs:int"/>
        <xs:attribute name="vehicleMounted" type="xs:boolean"/>
        <xs:attribute name="MinimumVitalityPoints" type="xs:int"/>
    </xs:complexType>
    <xs:complexType name="andType">
        <xs:choice maxOccurs="unbounded" minOccurs="0">
            <xs:element name="using" type="usingType"/>
            <xs:element name="player" type="playerType"/>
            <xs:element name="target" type="targetType"/>
            <xs:element name="not" type="notType"/>
            <xs:element name="game" type="gameType"/>
            <xs:element name="or" minOccurs="0" type="andType"/>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="gameType">
        <xs:attribute type="xs:string" name="night"/>
    </xs:complexType>
    <xs:complexType name="notType">
        <xs:sequence>
            <xs:element name="using" minOccurs="0" type="usingType"/>
            <xs:element name="player" minOccurs="0" type="playerType"/>
            <xs:element name="target" minOccurs="0" type="targetType"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="usingType">
        <xs:attribute type="xs:string" name="kind" use="optional"/>
        <xs:attribute type="xs:string" name="slot" use="optional"/>
        <xs:attribute type="xs:string" name="weaponChange" use="optional"/>
    </xs:complexType>
    <xs:complexType name="targetType">
        <xs:attribute name="levelRange" type="xs:token"/>
        <xs:attribute name="categoryType" type="xs:normalizedString"/>
    </xs:complexType>
    <xs:complexType name="enchantType">
        <xs:attribute name="order" type="xs:byte" use="optional"/>
        <xs:attribute name="stat" use="required" type="Stat"/>
        <xs:attribute name="val" type="xs:integer" fixed="0" use="required"/>
    </xs:complexType>
    <xs:complexType name="condType">
        <xs:choice maxOccurs="unbounded" minOccurs="0">
            <xs:element name="using" type="usingType"/>
            <xs:element name="and" type="andType"/>
            <xs:element name="not" type="notType"/>
            <xs:element name="player" type="playerType"/>
            <xs:element name="target" type="targetType"/>
        </xs:choice>
        <xs:attribute type="xs:short" name="msgId" use="optional"/>
        <xs:attribute type="xs:byte" name="addName" use="optional"/>
        <xs:attribute type="xs:string" name="msg" use="optional"/>
    </xs:complexType>


    <xs:complexType name="ItemStats">
        <xs:sequence>
            <xs:element name="stat" type="ItemStat" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ItemStat">
        <xs:attribute name="type" type="Stat"/>
        <xs:attribute name="value" type="xs:float"/>
    </xs:complexType>

    <xs:simpleType name="CommissionType">
        <xs:restriction base="xs:token">
            <xs:enumeration value="ONE_HAND_SWORD"/>
            <xs:enumeration value="ONE_HAND_MAGIC_SWORD"/>
            <xs:enumeration value="DAGGER"/>
            <xs:enumeration value="RAPIER"/>
            <xs:enumeration value="TWO_HAND_SWORD"/>
            <xs:enumeration value="ANCIENT_SWORD"/>
            <xs:enumeration value="DUALSWORD"/>
            <xs:enumeration value="DUAL_DAGGER"/>
            <xs:enumeration value="BLUNT_WEAPON"/>
            <xs:enumeration value="ONE_HAND_MAGIC_BLUNT_WEAPON"/>
            <xs:enumeration value="TWO_HAND_BLUNT_WEAPON"/>
            <xs:enumeration value="TWO_HAND_MAGIC_BLUNT_WEAPON"/>
            <xs:enumeration value="DUAL_BLUNT_WEAPON"/>
            <xs:enumeration value="BOW"/>
            <xs:enumeration value="CROSSBOW"/>
            <xs:enumeration value="FIST_WEAPON"/>
            <xs:enumeration value="SPEAR"/>
            <xs:enumeration value="OTHER_WEAPON"/>
            <xs:enumeration value="HELMET"/>
            <xs:enumeration value="ARMOR_TOP"/>
            <xs:enumeration value="ARMOR_PANTS"/>
            <xs:enumeration value="FULL_BODY"/>
            <xs:enumeration value="GLOVES"/>
            <xs:enumeration value="FEET"/>
            <xs:enumeration value="SHIELD"/>
            <xs:enumeration value="SIGIL"/>
            <xs:enumeration value="UNDERWEAR"/>
            <xs:enumeration value="CLOAK"/>
            <xs:enumeration value="RING"/>
            <xs:enumeration value="EARRING"/>
            <xs:enumeration value="NECKLACE"/>
            <xs:enumeration value="BELT"/>
            <xs:enumeration value="BRACELET"/>
            <xs:enumeration value="HAIR_ACCESSORY"/>
            <xs:enumeration value="POTION"/>
            <xs:enumeration value="SCROLL_ENCHANT_WEAPON"/>
            <xs:enumeration value="SCROLL_ENCHANT_ARMOR"/>
            <xs:enumeration value="SCROLL_OTHER"/>
            <xs:enumeration value="SOULSHOT"/>
            <xs:enumeration value="SPIRITSHOT"/>
            <xs:enumeration value="PET_EQUIPMENT"/>
            <xs:enumeration value="PET_SUPPLIES"/>
            <xs:enumeration value="CRYSTAL"/>
            <xs:enumeration value="RECIPE"/>
            <xs:enumeration value="MAJOR_CRAFTING_INGREDIENTS"/>
            <xs:enumeration value="LIFE_STONE"/>
            <xs:enumeration value="SOUL_CRYSTAL"/>
            <xs:enumeration value="ATTRIBUTE_STONE"/>
            <xs:enumeration value="WEAPON_ENCHANT_STONE"/>
            <xs:enumeration value="ARMOR_ENCHANT_STONE"/>
            <xs:enumeration value="SPELLBOOK"/>
            <xs:enumeration value="GEMSTONE"/>
            <xs:enumeration value="POUCH"/>
            <xs:enumeration value="PIN"/>
            <xs:enumeration value="MAGIC_RUNE_CLIP"/>
            <xs:enumeration value="MAGIC_ORNAMENT"/>
            <xs:enumeration value="DYES"/>
            <xs:enumeration value="OTHER_ITEM"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== DevMystogan/Datapack/gameserver/data/items/14300-14399.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://l2j.org" xsi:schemaLocation="http://l2j.org items.xsd">
	<weapon id="14327" name="Sirra's Blade" type="SWORD" body-part="TWO_HAND" icon="icon.weapon_sirr_blade_i00">
	<!-- For NPC -->
		<restriction freightable="false"/>
		<attributes weight="1300" price="26968400" commission-type="OTHER_ITEM"/>
		<crystal type="A"/>
		<damage radius="40" angle="240"/>
		<consume  soulshots="2" spiritshots="2"/>
		<stats>
			<stat type="pAtk" value="251.0"/>
			<stat type="mAtk" value="121.0"/>
			<stat type="rCrit" value="8.0"/>
			<stat type="pAtkSpd" value="379.0"/>
			<stat type="randomDamage" value="10.0"/>
			<stat type="pAtkRange" value="40.0"/>
		</stats>
	</weapon>

	<weapon id="14328" name="Sword of Ipos" type="TWO_HAND_SWORD" body-part="TWO_HAND" icon="icon.weapon_sword_of_ipos_i00">
	<!-- For NPC -->
		<restriction freightable="false"/>
		<attributes weight="1820" price="26968400" commission-type="OTHER_ITEM"/>
		<crystal type="A"/>
		<damage radius="40" angle="240"/>
		<consume  soulshots="2" spiritshots="2"/>
		<stats>
			<stat type="pAtk" value="305.0"/>
			<stat type="mAtk" value="121.0"/>
			<stat type="rCrit" value="8.0"/>
			<stat type="pAtkSpd" value="325.0"/>
			<stat type="randomDamage" value="10.0"/>
			<stat type="pAtkRange" value="40.0"/>
		</stats>
	</weapon>

	<weapon id="14330" name="Behemoth' Tuning Fork" type="HAMMER" body-part="TWO_HAND" icon="icon.weapon_tuning_fork_of_behemoth_i00">
	<!-- For NPC -->
		<restriction freightable="false"/>
		<attributes weight="1890" price="26968400" commission-type="OTHER_ITEM"/>
		<crystal type="A"/>
		<damage radius="40" angle="240"/>
		<consume  soulshots="2" spiritshots="2"/>
		<stats>
			<stat type="pAtk" value="305.0"/>
			<stat type="mAtk" value="121.0"/>
			<stat type="rCrit" value="6.0"/>
			<stat type="accCombat" value="8.0"/>
			<stat type="pAtkSpd" value="325.0"/>
			<stat type="randomDamage" value="20.0"/>
			<stat type="pAtkRange" value="40.0"/>
		</stats>
	</weapon>

	<weapon id="14331" name="Naga Storm" type="DAGGER" body-part="TWO_HAND" icon="icon.weapon_naga_storm_i00">
	<!-- For NPC -->
		<restriction freightable="false"/>
		<attributes weight="930" price="26968400" commission-type="OTHER_ITEM"/>
		<crystal type="A"/>
		<damage radius="40" angle="240"/>
		<consume  soulshots="2" spiritshots="2"/>
		<stats>
			<stat type="pAtk" value="220.0"/>
			<stat type="mAtk" value="121.0"/>
			<stat type="rCrit" value="12.0"/>
			<stat type="accCombat" value="-3.75"/>
			<stat type="pAtkSpd" value="433.0"/>
			<stat type="randomDamage" value="5.0"/>
			<stat type="pAtkRange" value="80.0"/>
		</stats>
	</weapon>

	<weapon id="14332" name="Tiphon's Spear" type="SPEAR" body-part="TWO_HAND" icon="icon.weapon_tiphon_spear_i00">
	<!-- For NPC -->
		<restriction freightable="false"/>
		<attributes weight="1820" price="26968400" commission-type="OTHER_ITEM"/>
		<crystal type="A"/>
		<damage radius="40" angle="240"/>
		<consume  soulshots="2" spiritshots="2"/>
		<stats>
			<stat type="pAtk" value="251.0"/>
			<stat type="mAtk" value="121.0"/>
			<stat type="rCrit" value="8.0"/>
			<stat type="accCombat" value="-3.75"/>
			<stat type="pAtkSpd" value="325.0"/>
			<stat type="randomDamage" value="10.0"/>
			<stat type="pAtkRange" value="80.0"/>
		</stats>
		<skills>
			<skill id="3599" level="1"/>  <!-- Polearm Multi-attack -->
		</skills>
	</weapon>

	<weapon id="14333" name="Shyeed's Bow" type="BOW" body-part="TWO_HAND" icon="icon.weapon_shyid_bow_i00">
	<!-- For NPC -->
		<restriction freightable="false"/>
		<attributes weight="1640" price="26968400" commission-type="OTHER_ITEM"/>
		<crystal type="A"/>
		<damage radius="40" angle="240"/>
		<consume  soulshots="3" spiritshots="2" mana="5"/>
		<stats>
			<stat type="pAtk" value="570.0"/>
			<stat type="mAtk" value="133.0"/>
			<stat type="rCrit" value="12.0"/>
			<stat type="accCombat" value="-3.75"/>
			<stat type="pAtkSpd" value="227.0"/>
			<stat type="randomDamage" value="5.0"/>
			<stat type="pAtkRange" value="500.0"/>
		</stats>
	</weapon>

	<weapon id="14334" name="Sobekk's Hurricane" type="FIST" body-part="TWO_HAND" icon="icon.weapon_sobekk_hurricane_i00">
	<!-- For NPC -->
		<restriction freightable="false"/>
		<attributes weight="1330" price="26968400" commission-type="OTHER_ITEM"/>
		<crystal type="A"/>
		<damage radius="40" angle="240"/>
		<consume  soulshots="2" spiritshots="2"/>
		<stats>
			<stat type="pAtk" value="305.0"/>
			<stat type="mAtk" value="121.0"/>
			<stat type="rCrit" value="6.0"/>
			<stat type="accCombat" value="8.0"/>
			<stat type="pAtkSpd" value="325.0"/>
			<stat type="randomDamage" value="5.0"/>
			<stat type="pAtkRange" value="40.0"/>
		</stats>
	</weapon>

	<weapon id="14335" name="Themis' Tongue" type="MAGIC_SWORD" body-part="TWO_HAND" icon="icon.weapon_tongue_of_themis_i00" magic="true">
	<!-- For NPC -->
		<restriction freightable="false"/>
		<attributes weight="820" price="26968400" commission-type="OTHER_ITEM"/>
		<crystal type="A"/>
		<damage radius="40" angle="240"/>
		<consume  soulshots="2" spiritshots="2"/>
		<stats>
			<stat type="pAtk" value="202.0"/>
			<stat type="mAtk" value="161.0"/>
			<stat type="rCrit" value="8.0"/>
			<stat type="pAtkSpd" value="379.0"/>
			<stat type="randomDamage" value="10.0"/>
			<stat type="pAtkRange" value="40.0"/>
		</stats>
	</weapon>

	<weapon id="14336" name="Cabrio's Hand" type="ROD" body-part="TWO_HAND" icon="icon.weapon_hand_of_cabrio_i00" magic="true">
	<!-- For NPC -->
		<restriction freightable="false"/>
		<attributes weight="1510" price="26968400" commission-type="OTHER_ITEM"/>
		<crystal type="A"/>
		<damage radius="40" angle="240"/>
		<consume  soulshots="2" spiritshots="2"/>
		<stats>
			<stat type="pAtk" value="202.0"/>
			<stat type="mAtk" value="161.0"/>
			<stat type="rCrit" value="6.0"/>
			<stat type="accCombat" value="8.0"/>
			<stat type="pAtkSpd" value="379.0"/>
			<stat type="randomDamage" value="20.0"/>
			<stat type="pAtkRange" value="40.0"/>
		</stats>
	</weapon>

	<weapon id="14338" name="Tallum Blade*Damascus" type="DUAL" body-part="TWO_HAND" icon="icon.weapon_dual_sword_i00">
	<!-- For NPC -->
		<restriction freightable="false"/>
		<attributes weight="1890" price="26968400" commission-type="OTHER_ITEM"/>
		<crystal type="A"/>
		<damage radius="40" angle="240"/>
		<consume  soulshots="2" spiritshots="2"/>
		<stats>
			<stat type="pAtk" value="305.0"/>
			<stat type="mAtk" value="121.0"/>
			<stat type="rCrit" value="8.0"/>
			<stat type="pAtkSpd" value="325.0"/>
			<stat type="randomDamage" value="10.0"/>
			<stat type="pAtkRange" value="40.0"/>
		</stats>
	</weapon>

	<weapon id="14339" name="Ã‰clair Bijou" type="RAPIER" body-part="RIGHT_HAND" icon="icon.weapon_greed_stinger_i00">
	<!-- For NPC -->
		<restriction freightable="false"/>
		<attributes weight="1300" price="26968400" commission-type="OTHER_ITEM"/>
		<crystal type="A"/>
		<damage radius="40" angle="240"/>
		<consume  soulshots="2" spiritshots="2"/>
		<stats>
			<stat type="pAtk" value="228.0"/>
			<stat type="mAtk" value="121.0"/>
			<stat type="rCrit" value="10.0"/>
			<stat type="accCombat" value="-1.5"/>
			<stat type="pAtkSpd" value="406.0"/>
			<stat type="randomDamage" value="40.0"/>
			<stat type="pAtkRange" value="40.0"/>
		</stats>
	</weapon>

	<weapon id="14341" name="Screaming Vengeance" type="CROSSBOW" body-part="TWO_HAND" icon="icon.weapon_soul_shooter_i00">
	<!-- For NPC -->
		<restriction freightable="false"/>
		<attributes weight="1640" price="26968400" commission-type="OTHER_ITEM"/>
		<crystal type="A"/>
		<damage radius="40" angle="240"/>
		<consume  soulshots="3" spiritshots="2"/>
		<stats>
			<stat type="pAtk" value="318.0"/>
			<stat type="mAtk" value="121.0"/>
			<stat type="rCrit" value="10.0"/>
			<stat type="accCombat" value="-1.5"/>
			<stat type="pAtkSpd" value="303.0"/>
			<stat type="randomDamage" value="10.0"/>
			<stat type="pAtkRange" value="400.0"/>
		</stats>
	</weapon>

	<armor id="14348" name="Majestic Earring" type="NONE" body-part="EAR" icon="icon.accessary_inferno_earing_i00">
	<!-- For NPC -->
		<restriction freightable="false"/>
		<attributes weight="150" price="1498000" />
		<crystal type="A"/>
		<stats>
			<stat type="mDef" value="63.0"/>
			<stat type="maxMp" value="25.0"/>
		</stats>
	</armor>

	<armor id="14349" name="Majestic Ring" type="NONE" body-part="FINGER" icon="icon.accessary_inferno_ring_i00">
	<!-- For NPC -->
		<restriction freightable="false"/>
		<attributes weight="150" price="999000" />
		<crystal type="A"/>
		<stats>
			<stat type="mDef" value="42.0"/>
			<stat type="maxMp" value="17.0"/>
		</stats>
	</armor>

	<armor id="14350" name="Majestic Necklace" type="NONE" body-part="NECK" icon="icon.accessary_inferno_necklace_i00">
	<!-- For NPC -->
		<restriction freightable="false"/>
		<attributes weight="150" price="1998000" />
		<crystal type="A"/>
		<stats>
			<stat type="mDef" value="85.0"/>
			<stat type="maxMp" value="33.0"/>
		</stats>
	</armor>

</list>

=== DevMystogan/Datapack/gameserver/data/items/custom/mana_potion.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://l2j.org" xsi:schemaLocation="http://l2j.org ../items.xsd">
    <item id="728" display-id="90310" type="POTION" name="Mana Potion" icon="icon.etc_reagent_blue_i00">
        <!-- Magical, liquid medicine that restores MP for a certain amount of time. -->
        <restriction stackable="true" olympiad-restricted="true"/>
        <condition add-name="true" msg-id="113">
            <player flying="false"/>
        </condition>
        <attributes weight="180" price="2000" commission-type="POTION" for-npc="true" immediate-effect="true"/>
        <skill-reducer type="ItemSkills">
            <skill id="26030" level="1"/>  <!-- Mana Potion -->
        </skill-reducer>
    </item>
</list>
