=== DevMystogan/Datapack/gameserver/data/xsd/DailyMission.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   targetNamespace="http://l2j.org"
		   xmlns="http://l2j.org"
		   elementFormDefault="qualified">

	<xs:include schemaLocation="common.xsd"/>

	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element type="MissionType" name="mission" maxOccurs="unbounded" minOccurs="0" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="MissionType">
		<xs:sequence>
			<xs:element type="shortList" name="classes" minOccurs="0" />
			<xs:element type="handlerType" name="handler" minOccurs="0" maxOccurs="unbounded" />
			<xs:element type="RewardType" name="reward" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute type="xs:short" name="id" use="required"/>
		<xs:attribute type="xs:string" name="name" use="required"/>
		<xs:attribute type="xs:short" name="requiredCompletion" default="1"/>
		<xs:attribute type="Cycle" name="cycle" default="DAILY"/>
		<xs:attribute type="xs:boolean" name="isDisplayedWhenNotAvailable" />
	</xs:complexType>

	<xs:complexType name="handlerType">
		<xs:sequence>
			<xs:element type="paramType" name="param" maxOccurs="unbounded" minOccurs="0" />
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="paramType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="name" type="xs:string" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="RewardType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:int" name="id" use="required"/>
				<xs:attribute type="xs:int" name="count" default="1"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:simpleType name="Cycle">
		<xs:restriction base="xs:string">
			<xs:whiteSpace value="collapse"/>
			<xs:enumeration value="DAILY"/>
			<xs:enumeration value="WEEKLY"/>
			<xs:enumeration value="MONTHLY"/>
			<xs:enumeration value="SINGLE"/>
		</xs:restriction>
	</xs:simpleType>

</xs:schema>

=== DevMystogan/Datapack/gameserver/data/DailyMission.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://l2j.org" xsi:schemaLocation="http://l2j.org xsd/DailyMission.xsd">

    <mission id="24" name="Reach Level (Lv. 2)" requiredCompletion="2" cycle="SINGLE">
        <handler name="level"/>
        <reward id="29651" count="5"/>
    </mission>

    <mission id="25" name="Reach Level (Lv. 3)" requiredCompletion="3" cycle="SINGLE">
        <handler name="level"/>
        <reward id="29651" count="10"/>
    </mission>

    <mission id="26" name="Reach Level (Lv. 4)" requiredCompletion="4" cycle="SINGLE">
        <handler name="level"/>
        <reward id="10650"/>
    </mission>

    <mission id="27" name="Reach Level (Lv. 5)" requiredCompletion="5" cycle="SINGLE">
        <handler name="level"/>
        <reward id="29651" count="10"/>
    </mission>

    <mission id="28" name="Reach Level (Lv. 6)" requiredCompletion="6" cycle="SINGLE">
        <handler name="level"/>
        <reward id="29648" count="2"/>
    </mission>

    <mission id="29" name="Reach Level (Lv. 7)" requiredCompletion="7" cycle="SINGLE">
        <handler name="level"/>
        <reward id="29654" count="2"/>
    </mission>

    <mission id="30" name="Reach Level (Lv. 8)" requiredCompletion="8" cycle="SINGLE">
        <handler name="level"/>
        <reward id="29651" count="10"/>
    </mission>

    <mission id="31" name="Reach Level (Lv. 9)" requiredCompletion="9" cycle="SINGLE">
        <handler name="level"/>
        <reward id="10650" count="5"/>
    </mission>

    <mission id="32" name="Reach Level (Lv. 10 Warrior only)" requiredCompletion="10" cycle="SINGLE">
        <classes>0 18 31 44 53 1 4 19 32 45 56 2 3 5 6 20 21 33 34 46 57 88 89 90 91 99 100 106 107 113 117 118</classes>
        <handler name="level"/>
        <reward id="70095"/>
        <reward id="70096"/>
        <reward id="70097"/>
    </mission>

    <mission id="32" name="Reach Level (Lv. 10 Warrior only)" requiredCompletion="10" cycle="SINGLE">
        <classes>7 22 35 47 8 9 23 24 36 37 54 55 48 92 93 101 102 108 109 114 115 116</classes>
        <handler name="level"/>
        <reward id="70095"/>
        <reward id="70096"/>
        <reward id="70097"/>
    </mission>

    <mission id="32" name="Reach Level (Lv. 10 Wizard only)" requiredCompletion="10">
        <classes>10 25 38 11 15 26 29 39 42 12 13 14 16 17 27 28 30 40 41 43 49 50 51 52 94 95 96 97 98 103 104 105 110 111 112</classes>
        <handler name="level"/>
        <reward id="70098"/>
        <reward id="70099"/>
        <reward id="70100"/>
    </mission>

    <mission id="33" name="Reach Level (Lv. 11)" requiredCompletion="11" cycle="SINGLE">
        <handler name="level"/>
        <reward id="29651" count="10"/>
        <reward id="49036" count="5"/>
    </mission>

    <mission id="34" name="Reach Level (Lv. 12)" requiredCompletion="12" cycle="SINGLE">
        <handler name="level"/>
        <reward id="29648" count="3"/>
    </mission>

    <mission id="35" name="Reach Level (Lv. 13)" requiredCompletion="13" cycle="SINGLE">
        <handler name="level"/>
        <reward id="29654" count="3"/>
    </mission>

    <mission id="36" name="Reach Level (Lv. 14)" requiredCompletion="14" cycle="SINGLE">
        <handler name="level"/>
        <reward id="29652" count="15"/>
    </mission>

    <mission id="37" name="Reach Level (Lv. 15)" requiredCompletion="15" cycle="SINGLE">
        <handler name="level"/>
        <reward id="29648" count="2"/>
    </mission>

    <mission id="38" name="Reach Level (Lv. 16)" requiredCompletion="16" cycle="SINGLE">
        <handler name="level"/>
        <reward id="29648" count="2"/>
    </mission>

    <mission id="39" name="Reach Level (Lv. 17)" requiredCompletion="17" cycle="SINGLE">
        <handler name="level"/>
        <reward id="29654" count="3"/>
    </mission>

    <mission id="40" name="Reach Level (Lv. 18 Warrior only)" requiredCompletion="18" cycle="SINGLE">
        <classes>0 18 31 44 53 1 4 19 32 45 56 2 3 5 6 20 21 33 34 46 57 88 89 90 91 99 100 106 107 113 117 118
        </classes>
        <handler name="level"/>
        <reward id="70102" count="10"/>
    </mission>

    <mission id="40" name="Reach Level (Lv. 18 Warrior only)" requiredCompletion="18" cycle="SINGLE">
        <classes>7 22 35 47 8 9 23 24 36 37 54 55 48 92 93 101 102 108 109 114 115 116</classes>
        <handler name="level"/>
        <reward id="70102" count="10"/>
    </mission>

    <mission id="40" name="Reach Level (Lv. 18 Wizard only)" requiredCompletion="18" cycle="SINGLE">
        <classes>10 25 38 11 15 26 29 39 42 12 13 14 16 17 27 28 30 40 41 43 49 50 51 52 94 95 96 97 98 103 104 105 110 111 112</classes>
        <handler name="level"/>
        <reward id="70103" count="10"/>
    </mission>

    <mission id="41" name="Reach Level (Lv. 19)" requiredCompletion="19" cycle="SINGLE">
        <handler name="level"/>
        <reward id="49036" count="10"/>
    </mission>

    <mission id="42" name="Reach Level (Lv. 20)" requiredCompletion="20" cycle="SINGLE">
        <handler name="level"/>
        <reward id="70024" count="20"/>
    </mission>

    <mission id="43" name="Reach Level (Lv. 21)" requiredCompletion="21" cycle="SINGLE">
        <handler name="level"/>
        <reward id="29648" count="2"/>
    </mission>

    <mission id="44" name="Reach Level (Lv. 22)" requiredCompletion="22" cycle="SINGLE">
        <handler name="level"/>
        <reward id="29654" count="3"/>
    </mission>

    <mission id="45" name="Reach Level (Lv. 23 Warrior only)" requiredCompletion="23" cycle="SINGLE">
        <classes>0 18 31 44 53 1 4 19 32 45 56 2 3 5 6 20 21 33 34 46 57 88 89 90 91 99 100 106 107 113 117 118</classes>
        <handler name="level"/>
        <reward id="70104" count="3"/>
    </mission>

    <mission id="45" name="Reach Level (Lv. 23 Warrior only)" requiredCompletion="23" cycle="SINGLE">
        <classes>7 22 35 47 8 9 23 24 36 37 54 55 48 92 93 101 102 108 109 114 115 116</classes>
        <handler name="level"/>
        <reward id="70102" count="10"/>
    </mission>

    <mission id="45" name="Reach Level (Lv. 23 Wizard only)" requiredCompletion="23" cycle="SINGLE">
        <classes>10 25 38 11 15 26 29 39 42 12 13 14 16 17 27 28 30 40 41 43 49 50 51 52 94 95 96 97 98 103 104 105 110 111 112</classes>
        <handler name="level"/>
        <reward id="70105" count="3"/>
    </mission>

    <mission id="46" name="Reach Level (Lv. 24)" requiredCompletion="24" cycle="SINGLE">
        <handler name="level"/>
        <reward id="29648" count="2"/>
        <reward id="49693"/>
    </mission>

    <mission id="47" name="Reach Level (Lv. 25)" requiredCompletion="25" cycle="SINGLE">
        <handler name="level"/>
        <reward id="29654" count="3"/>
    </mission>

    <mission id="48" name="Reach Level (Lv. 26)" requiredCompletion="26" cycle="SINGLE">
        <handler name="level"/>
        <reward id="29648" count="2"/>
    </mission>

    <mission id="49" name="Reach Level (Lv. 27)" requiredCompletion="27" cycle="SINGLE">
        <handler name="level"/>
        <reward id="29654" count="3"/>
    </mission>

    <mission id="50" name="Reach Level (Lv. 28 Warrior only)" requiredCompletion="28" cycle="SINGLE">
        <classes>0 18 31 44 53 1 4 19 32 45 56 2 3 5 6 20 21 33 34 46 57 88 89 90 91 99 100 106 107 113 117 118</classes>
        <handler name="level"/>
        <reward id="70104" count="3"/>
    </mission>

    <mission id="50" name="Reach Level (Lv. 28 Warrior only)" requiredCompletion="28" cycle="SINGLE">
        <classes>7 22 35 47 8 9 23 24 36 37 54 55 48 92 93 101 102 108 109 114 115 116</classes>
        <handler name="level"/>
        <reward id="70104" count="3"/>
    </mission>

    <mission id="50" name="Reach Level (Lv. 28 Wizard only)" requiredCompletion="28" cycle="SINGLE">
        <classes>10 25 38 11 15 26 29 39 42 12 13 14 16 17 27 28 30 40 41 43 49 50 51 52 94 95 96 97 98 103 104 105 110 111 112</classes>
        <handler name="level"/>
        <reward id="70105" count="3"/>
    </mission>

    <mission id="51" name="Reach Level (Lv. 29)" requiredCompletion="29" cycle="SINGLE">
        <handler name="level"/>
        <reward id="29648" count="2"/>
    </mission>

    <mission id="52" name="Reach Level (Lv. 30)" requiredCompletion="30" cycle="SINGLE">
        <handler name="level"/>
        <reward id="29648" count="3"/>
    </mission>

    <mission id="53" name="Reach Level (Lv. 31)" requiredCompletion="31" cycle="SINGLE">
        <handler name="level"/>
        <reward id="29648" count="2"/>
    </mission>

    <mission id="54" name="Reach Level (Lv. 32)" requiredCompletion="32" cycle="SINGLE">
        <handler name="level"/>
        <reward id="29654" count="3"/>
    </mission>

    <mission id="55" name="Reach Level (Lv. 33)" requiredCompletion="33" cycle="SINGLE">
        <handler name="level"/>
        <reward id="70107" count="3"/>
    </mission>

    <mission id="56" name="Reach Level (Lv. 34)" requiredCompletion="34" cycle="SINGLE">
        <handler name="level"/>
        <reward id="29648" count="2"/>
    </mission>

    <mission id="57" name="Reach Level (Lv. 35)" requiredCompletion="35" cycle="SINGLE">
        <handler name="level"/>
        <reward id="29648" count="3"/>
    </mission>

    <mission id="58" name="Reach Level (Lv. 36)" requiredCompletion="36" cycle="SINGLE">
        <handler name="level"/>
        <reward id="29654" count="3"/>
    </mission>

    <mission id="59" name="Reach Level (Lv. 37)" requiredCompletion="37" cycle="SINGLE">
        <handler name="level"/>
        <reward id="70107" count="3"/>
    </mission>

    <mission id="60" name="Reach Level (Lv. 38 Warrior only)" requiredCompletion="38" cycle="SINGLE">
        <classes>0 18 31 44 53 1 4 19 32 45 56 2 3 5 6 20 21 33 34 46 57 88 89 90 91 99 100 106 107 113 117 118</classes>
        <handler name="level"/>
        <reward id="70104" count="3"/>
