=== DevMystogan/Datapack/gameserver/data/mapregion/MapRegion.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   targetNamespace="http://l2j.org"
		   xmlns="http://l2j.org"
		   elementFormDefault="qualified">

	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="region" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="respawnPoint" type="RespawnType" maxOccurs="unbounded"/>
							<xs:element name="map" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="X" type="xs:integer" use="required" />
									<xs:attribute name="Y" type="xs:integer" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element name="banned" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="point" type="xs:token" use="required" />
									<xs:attribute name="race" type="RaceType" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="castle" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:nonNegativeInteger">
									<xs:minInclusive value="0" />
									<xs:maxInclusive value="9" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="bbs" type="xs:token" use="required" />
						<xs:attribute name="locId" type="xs:positiveInteger" use="required" />
						<xs:attribute name="name" type="xs:token" use="required" />
						<xs:attribute name="town" type="xs:token" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="enabled" type="xs:boolean" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:simpleType name="RaceType">
		<xs:restriction base="xs:token">
			<xs:enumeration value="DARK_ELF" />
			<xs:enumeration value="DWARF" />
			<xs:enumeration value="ELF" />
			<xs:enumeration value="HUMAN" />
			<xs:enumeration value="ORC" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="Location">
		<xs:attribute name="x" type="xs:int" use="required"/>
		<xs:attribute name="y" type="xs:int" use="required"/>
		<xs:attribute name="z" type="xs:int" use="required"/>
	</xs:complexType>

	<xs:complexType name="RespawnType">
		<xs:complexContent>
			<xs:extension base="Location">
				<xs:attribute name="isChaotic" type="xs:boolean" default="false"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>

=== DevMystogan/Datapack/gameserver/data/mapregion/giran_habor.xml
<?xml version="1.0" encoding="UTF-8"?>


<list enabled="true"
	  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	  xmlns="http://l2j.org"
	  xsi:schemaLocation="http://l2j.org MapRegion.xsd" >

	<!-- Giran Habor -->
	<region name="giran_habor" town="Giran Habor" locId="919" bbs="6">
		<respawnPoint x="46763" y="187041" z="-3451" />
		<respawnPoint x="46471" y="186666" z="-3451" />
		<respawnPoint x="47290" y="186842" z="-3451" />
		<respawnPoint x="47038" y="186506" z="-3451" />
		<respawnPoint x="47684" y="186682" z="-3451" />
		<respawnPoint x="47450" y="186347" z="-3451" />
		<respawnPoint x="48715" y="185873" z="-3451" />
		<respawnPoint x="48363" y="185518" z="-3451" />
		<respawnPoint x="48757" y="185124" z="-3451" />
		<respawnPoint x="49034" y="185512" z="-3451" />
		<respawnPoint x="49033" y="184647" z="-3451" />
		<respawnPoint x="49372" y="185076" z="-3451" />
		<respawnPoint x="46763" y="187041" z="-3451" chaotic="true" />
		<respawnPoint x="46471" y="186666" z="-3451" chaotic="true" />
		<respawnPoint x="47290" y="186842" z="-3451" chaotic="true" />
		<respawnPoint x="47038" y="186506" z="-3451" chaotic="true" />
		<respawnPoint x="47684" y="186682" z="-3451" chaotic="true" />
		<respawnPoint x="47450" y="186347" z="-3451" chaotic="true" />
		<respawnPoint x="48715" y="185873" z="-3451" chaotic="true" />
		<respawnPoint x="48363" y="185518" z="-3451" chaotic="true" />
		<respawnPoint x="48757" y="185124" z="-3451" chaotic="true" />
		<respawnPoint x="49034" y="185512" z="-3451" chaotic="true" />
		<respawnPoint x="49033" y="184647" z="-3451" chaotic="true" />
		<respawnPoint x="49372" y="185076" z="-3451" chaotic="true" />
		<map X="20" Y="24" />
		<map X="21" Y="24" />
		<map X="21" Y="25" />
	</region>
</list>

=== DevMystogan/Datapack/gameserver/data/mapregion/rift_bitween_worlds.xml
<?xml version="1.0" encoding="UTF-8"?>

<list enabled="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	  xmlns="http://l2j.org"
	  xsi:schemaLocation="http://l2j.org MapRegion.xsd">
	<!-- Rift Bitween Worlds -->
	<region name="rift_bitween_worlds" town="Dimensional Rift" locId="1643" bbs="100">
		<respawnPoint x="146950" y="26754" z="-2198" />
		<respawnPoint x="136398" y="28901" z="-3582" isChaotic="true" />
		<respawnPoint x="137292" y="28485" z="-3290" isChaotic="true" />
		<respawnPoint x="155925" y="28554" z="-3164" isChaotic="true" />
		<respawnPoint x="157608" y="23866" z="-3760" isChaotic="true" />
		<respawnPoint x="157463" y="28770" z="-3371" isChaotic="true" />
		<respawnPoint x="159348" y="28561" z="-3400" isChaotic="true" />
		<respawnPoint x="160236" y="14119" z="-3892" isChaotic="true" />
		<respawnPoint x="156764" y="13774" z="-3960" isChaotic="true" />
		<respawnPoint x="161426" y="23055" z="-3670" isChaotic="true" />
		<respawnPoint x="136380" y="21899" z="-3647" isChaotic="true" />
		<respawnPoint x="137708" y="15640" z="-3800" isChaotic="true" />
		<respawnPoint x="136629" y="28127" z="-3258" isChaotic="true" />
		<map X="16" Y="12" />
	</region>
</list>

=== DevMystogan/Datapack/gameserver/data/mapregion/darkelf_town.xml
<?xml version="1.0" encoding="UTF-8"?>

<list enabled="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	  xmlns="http://l2j.org"
	  xsi:schemaLocation="http://l2j.org MapRegion.xsd">
	<!-- Darkelf Town -->
	<region name="darkelf_town" town="Darkelven Town" locId="915" bbs="3">
		<respawnPoint x="12501" y="16768" z="-4500" />
		<respawnPoint x="12104" y="17385" z="-4500" />
		<respawnPoint x="12519" y="16376" z="-4500" />
		<respawnPoint x="10355" y="17270" z="-4500" />
		<respawnPoint x="10146" y="16965" z="-4500" />
		<respawnPoint x="10691" y="16343" z="-4500" />
		<respawnPoint x="3040" y="24240" z="-3700" chaotic="true" />
		<respawnPoint x="1184" y="21856" z="-3240" chaotic="true" />
		<respawnPoint x="3760" y="25136" z="-3700" chaotic="true" />
		<respawnPoint x="672" y="20096" z="-3350" chaotic="true" />
		<respawnPoint x="1248" y="14512" z="-3180" chaotic="true" />
		<respawnPoint x="-8176" y="23120" z="-3450" chaotic="true" />
		<respawnPoint x="-10208" y="25408" z="-3560" chaotic="true" />
		<respawnPoint x="-11456" y="23936" z="-3700" chaotic="true" />
		<respawnPoint x="-9632" y="22624" z="-3650" chaotic="true" />
		<respawnPoint x="-5776" y="22080" z="-3510" chaotic="true" />
		<respawnPoint x="2224" y="11936" z="-3050" chaotic="true" />
		<respawnPoint x="1744" y="8640" z="-3250" chaotic="true" />
		<respawnPoint x="2784" y="7872" z="-3110" chaotic="true" />
		<respawnPoint x="3216" y="10128" z="-2980" chaotic="true" />
		<respawnPoint x="3584" y="6976" z="-3020" chaotic="true" />
		<respawnPoint x="-10768" y="21952" z="-3600" chaotic="true" />
		<respawnPoint x="-11360" y="22688" z="-3600" chaotic="true" />
		<respawnPoint x="-12784" y="23232" z="-3630" chaotic="true" />
		<respawnPoint x="-13632" y="21872" z="-3620" chaotic="true" />
		<respawnPoint x="-11984" y="21232" z="-3600" chaotic="true" />
		<map X="20" Y="18" />
		<map X="19" Y="18" />
		<map X="19" Y="19" />
		<map X="18" Y="19" />
		<map X="18" Y="18" />
		<map X="18" Y="20" />
		<map X="17" Y="19" />
		<banned race="ELF" point="elf_town" />
	</region>
	<!-- Temple Of Shilen -->
	<region name="Temple_of_Shilen" town="Darkelven Town" locId="915" bbs="3">
		<respawnPoint x="28295" y="11063" z="-4224" />
		<respawnPoint x="28302" y="11008" z="-4224" />
		<respawnPoint x="28377" y="10916" z="-4224" />
		<respawnPoint x="28456" y="10997" z="-4224" />
		<respawnPoint x="28461" y="11044" z="-4224" />
		<respawnPoint x="28395" y="11127" z="-4224" />
		<respawnPoint x="3040" y="24240" z="-3700" chaotic="true" />
		<respawnPoint x="1184" y="21856" z="-3240" chaotic="true" />
		<respawnPoint x="3760" y="25136" z="-3700" chaotic="true" />
		<respawnPoint x="672" y="20096" z="-3350" chaotic="true" />
		<respawnPoint x="1248" y="14512" z="-3180" chaotic="true" />
		<respawnPoint x="-8176" y="23120" z="-3450" chaotic="true" />
		<respawnPoint x="-10208" y="25408" z="-3560" chaotic="true" />
		<respawnPoint x="-11456" y="23936" z="-3700" chaotic="true" />
		<respawnPoint x="-9632" y="22624" z="-3650" chaotic="true" />
		<respawnPoint x="-5776" y="22080" z="-3510" chaotic="true" />
		<respawnPoint x="2224" y="11936" z="-3050" chaotic="true" />
		<respawnPoint x="1744" y="8640" z="-3250" chaotic="true" />
		<respawnPoint x="2784" y="7872" z="-3110" chaotic="true" />
		<respawnPoint x="3216" y="10128" z="-2980" chaotic="true" />
		<respawnPoint x="3584" y="6976" z="-3020" chaotic="true" />
		<respawnPoint x="-10768" y="21952" z="-3600" chaotic="true" />
		<respawnPoint x="-11360" y="22688" z="-3600" chaotic="true" />
		<respawnPoint x="-12784" y="23232" z="-3630" chaotic="true" />
		<respawnPoint x="-13632" y="21872" z="-3620" chaotic="true" />
		<respawnPoint x="-11984" y="21232" z="-3600" chaotic="true" />
		<banned race="ELF" point="elf_town" />
	</region>
</list>

=== DevMystogan/Datapack/gameserver/data/mapregion/elf_town.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- TODO: Remove "castle" attributes from here, it should be loaded from TaxZones -->
<list enabled="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns="http://l2j.org"
      xsi:schemaLocation="http://l2j.org MapRegion.xsd">
	<!-- Elf Town -->
	<region name="elf_town" town="Elven Town" castle="4" locId="914" bbs="4">
		<respawnPoint x="45487" y="49767" z="-2950" />
		<respawnPoint x="45080" y="49614" z="-2950" />
		<respawnPoint x="45284" y="49309" z="-2950" />
		<respawnPoint x="45576" y="49412" z="-2950" />
		<respawnPoint x="45896" y="49831" z="-2950" />
		<respawnPoint x="45463" y="50097" z="-2950" />
		<respawnPoint x="44935" y="49798" z="-2950" />
		<respawnPoint x="44798" y="49475" z="-2950" />
		<respawnPoint x="45100" y="49025" z="-2950" />
		<respawnPoint x="45912" y="49363" z="-2950" />
		<respawnPoint x="45788" y="49861" z="-2950" />
		<respawnPoint x="45325" y="50067" z="-2950" />
		<respawnPoint x="40720" y="56064" z="-3580" isChaotic="true" />
		<respawnPoint x="39760" y="55040" z="-3410" isChaotic="true" />
		<respawnPoint x="43152" y="55920" z="-3620" isChaotic="true" />
		<respawnPoint x="44192" y="56960" z="-3580" isChaotic="true" />
		<respawnPoint x="39328" y="56256" z="-3580" isChaotic="true" />
		<respawnPoint x="40448" y="57744" z="-3600" isChaotic="true" />
		<respawnPoint x="38080" y="52048" z="-3500" isChaotic="true" />
		<respawnPoint x="38784" y="51824" z="-3470" isChaotic="true" />
		<respawnPoint x="37088" y="51248" z="-3400" isChaotic="true" />
		<respawnPoint x="37952" y="49680" z="-3480" isChaotic="true" />
		<respawnPoint x="38848" y="47072" z="-3580" isChaotic="true" />
		<respawnPoint x="36688" y="49856" z="-3440" isChaotic="true" />
		<respawnPoint x="36096" y="46544" z="-3680" isChaotic="true" />
		<respawnPoint x="37200" y="45232" z="-3600" isChaotic="true" />
		<respawnPoint x="50128" y="55472" z="-3410" isChaotic="true" />
		<respawnPoint x="51856" y="54432" z="-3320" isChaotic="true" />
		<respawnPoint x="53136" y="54592" z="-3420" isChaotic="true" />
		<respawnPoint x="51824" y="58624" z="-3400" isChaotic="true" />
		<respawnPoint x="51232" y="59216" z="-3320" isChaotic="true" />
		<respawnPoint x="49808" y="56240" z="-3430" isChaotic="true" />
		<map X="21" Y="19" />
		<map X="21" Y="20" />
		<map X="20" Y="19" />
		<map X="20" Y="20" />
		<banned race="DARK_ELF" point="darkelf_town" />
	</region>
	<!-- Mothertree Glade -->
	<region name="Mothertree_Glade" town="Elven Town" castle="4" locId="914" bbs="4">
		<respawnPoint x="46045" y="41251" z="-3440" />
		<respawnPoint x="46117" y="41247" z="-3440" />
		<respawnPoint x="46182" y="41198" z="-3440" />
		<respawnPoint x="46115" y="41141" z="-3440" />
		<respawnPoint x="46048" y="41141" z="-3440" />
		<respawnPoint x="45978" y="41196" z="-3440" />
		<respawnPoint x="40720" y="56064" z="-3580" isChaotic="true" />
		<respawnPoint x="39760" y="55040" z="-3410" isChaotic="true" />
		<respawnPoint x="43152" y="55920" z="-3620" isChaotic="true" />
		<respawnPoint x="44192" y="56960" z="-3580" isChaotic="true" />
		<respawnPoint x="39328" y="56256" z="-3580" isChaotic="true" />
		<respawnPoint x="40448" y="57744" z="-3600" isChaotic="true" />
		<respawnPoint x="38080" y="52048" z="-3500" isChaotic="true" />
		<respawnPoint x="38784" y="51824" z="-3470" isChaotic="true" />
		<respawnPoint x="37088" y="51248" z="-3400" isChaotic="true" />
		<respawnPoint x="37952" y="49680" z="-3480" isChaotic="true" />
		<respawnPoint x="38848" y="47072" z="-3580" isChaotic="true" />
		<respawnPoint x="36688" y="49856" z="-3440" isChaotic="true" />
		<respawnPoint x="36096" y="46544" z="-3680" isChaotic="true" />
		<respawnPoint x="37200" y="45232" z="-3600" isChaotic="true" />
		<respawnPoint x="50128" y="55472" z="-3410" isChaotic="true" />
		<respawnPoint x="51856" y="54432" z="-3320" isChaotic="true" />
		<respawnPoint x="53136" y="54592" z="-3420" isChaotic="true" />
		<respawnPoint x="51824" y="58624" z="-3400" isChaotic="true" />
		<respawnPoint x="51232" y="59216" z="-3320" isChaotic="true" />
		<respawnPoint x="49808" y="56240" z="-3430" isChaotic="true" />
		<banned race="DARK_ELF" point="darkelf_town" />
	</region>
</list>

=== DevMystogan/Datapack/gameserver/data/mapregion/giran_castle_town.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- TODO: Remove "castle" attributes from here, it should be loaded from TaxZones -->
<list enabled="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	  xmlns="http://l2j.org"
	  xsi:schemaLocation="http://l2j.org MapRegion.xsd">
	<!-- Giran Castle Town -->
	<region name="giran_castle_town" town="Giran Castle Town" castle="3" locId="918" bbs="6">
		<respawnPoint x="82480" y="149087" z="-3350" />
		<respawnPoint x="81440" y="149119" z="-3350" />
		<respawnPoint x="81376" y="148095" z="-3350" />
		<respawnPoint x="82496" y="148095" z="-3350" />
		<respawnPoint x="83473" y="149223" z="-3300" />
		<respawnPoint x="83426" y="148835" z="-3300" />
		<respawnPoint x="83409" y="148578" z="-3300" />
		<respawnPoint x="83415" y="148235" z="-3300" />
		<respawnPoint x="82272" y="147801" z="-3350" />
		<respawnPoint x="81562" y="147782" z="-3350" />
		<respawnPoint x="81062" y="148144" z="-3350" />
		<respawnPoint x="81033" y="148883" z="-3350" />
		<respawnPoint x="81637" y="149427" z="-3350" />
		<respawnPoint x="82292" y="149450" z="-3350" />
		<respawnPoint x="74450" y="144238" z="-3730" isChaotic="true" />
		<respawnPoint x="74209" y="142395" z="-3730" isChaotic="true" />
		<respawnPoint x="77279" y="145045" z="-3630" isChaotic="true" />
		<respawnPoint x="74809" y="146119" z="-3600" isChaotic="true" />
		<respawnPoint x="75006" y="143520" z="-3700" isChaotic="true" />
		<respawnPoint x="81347" y="140579" z="-3520" isChaotic="true" />
		<respawnPoint x="79543" y="142050" z="-3500" isChaotic="true" />
		<respawnPoint x="86223" y="140993" z="-3400" isChaotic="true" />
		<respawnPoint x="78692" y="154573" z="-3450" isChaotic="true" />
		<respawnPoint x="77870" y="156209" z="-3430" isChaotic="true" />
		<respawnPoint x="79832" y="154009" z="-3500" isChaotic="true" />
		<respawnPoint x="75501" y="147178" z="-3530" isChaotic="true" />
		<map X="21" Y="23" />
		<map X="22" Y="22" />
		<map X="23" Y="22" />
		<!-- Heiness region -->
		<map X="22" Y="23" />
		<map X="22" Y="24" />
		<map X="22" Y="25" />
		<map X="23" Y="23" />
		<map X="23" Y="24" />
		<map X="23" Y="25" />
	</region>
</list>

=== DevMystogan/Datapack/gameserver/data/mapregion/orc_town.xml
<?xml version="1.0" encoding="UTF-8"?>

<list enabled="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	  xmlns="http://l2j.org"
	  xsi:schemaLocation="http://l2j.org MapRegion.xsd">
	<!-- Orc Town -->
	<region name="orc_town" town="Orc Town" locId="920" bbs="9">
		<respawnPoint x="-44316" y="-113136" z="-80" />
		<respawnPoint x="-44296" y="-114048" z="-80" />
		<respawnPoint x="-44704" y="-112896" z="-80" />
		<respawnPoint x="-44720" y="-114304" z="-80" />
		<respawnPoint x="-44206" y="-113392" z="-80" />
		<respawnPoint x="-43970" y="-114150" z="-80" />
		<respawnPoint x="-44328" y="-114625" z="-80" />
		<respawnPoint x="-44884" y="-115063" z="-80" />
		<respawnPoint x="-44923" y="-114659" z="-80" />
		<respawnPoint x="-44232" y="-113701" z="-80" />
		<respawnPoint x="-44596" y="-112956" z="-80" />
		<respawnPoint x="-44987" y="-112394" z="-80" />
		<respawnPoint x="-45498" y="-111800" z="-80" />
		<respawnPoint x="-44637" y="-112373" z="-80" />
		<respawnPoint x="-44189" y="-113065" z="-80" />
		<respawnPoint x="-44048" y="-113463" z="-80" />
		<respawnPoint x="-43552" y="-121488" z="-233" isChaotic="true" />
		<respawnPoint x="-42560" y="-121344" z="-188" isChaotic="true" />
		<respawnPoint x="-41536" y="-122960" z="-308" isChaotic="true" />
		<respawnPoint x="-40464" y="-122752" z="-364" isChaotic="true" />
		<respawnPoint x="-45568" y="-107296" z="-516" isChaotic="true" />
		<respawnPoint x="-46512" y="-106032" z="-700" isChaotic="true" />
		<respawnPoint x="-44304" y="-105888" z="-1156" isChaotic="true" />
		<respawnPoint x="-43728" y="-106688" z="-1304" isChaotic="true" />
		<respawnPoint x="-40000" y="-109200" z="-1736" isChaotic="true" />
		<respawnPoint x="-39792" y="-110832" z="-1860" isChaotic="true" />
		<respawnPoint x="-39136" y="-112688" z="-1844" isChaotic="true" />
		<respawnPoint x="-37888" y="-112608" z="-1772" isChaotic="true" />
		<map X="18" Y="14" />
		<map X="19" Y="13" />
		<map X="19" Y="14" />
		<map X="19" Y="15" />
		<map X="19" Y="16" />
		<map X="20" Y="13" />
		<map X="20" Y="14" />
		<map X="20" Y="15" />
	</region>
	<!-- Temple Of Paagrio -->
	<region name="Temple_of_Paagrio" town="Orc Town" locId="920" bbs="9">
		<respawnPoint x="-56733" y="-113459" z="-690" />
		<respawnPoint x="-56686" y="-113470" z="-690" />
		<respawnPoint x="-56728" y="-113610" z="-690" />
		<respawnPoint x="-56693" y="-113610" z="-690" />
		<respawnPoint x="-56743" y="-113757" z="-690" />
		<respawnPoint x="-56682" y="-113730" z="-690" />
		<respawnPoint x="-43552" y="-121488" z="-233" isChaotic="true" />
		<respawnPoint x="-42560" y="-121344" z="-188" isChaotic="true" />
		<respawnPoint x="-41536" y="-122960" z="-308" isChaotic="true" />
		<respawnPoint x="-40464" y="-122752" z="-364" isChaotic="true" />
		<respawnPoint x="-45568" y="-107296" z="-516" isChaotic="true" />
		<respawnPoint x="-46512" y="-106032" z="-700" isChaotic="true" />
		<respawnPoint x="-44304" y="-105888" z="-1156" isChaotic="true" />
		<respawnPoint x="-43728" y="-106688" z="-1304" isChaotic="true" />
		<respawnPoint x="-40000" y="-109200" z="-1736" isChaotic="true" />
		<respawnPoint x="-39792" y="-110832" z="-1860" isChaotic="true" />
		<respawnPoint x="-39136" y="-112688" z="-1844" isChaotic="true" />
		<respawnPoint x="-37888" y="-112608" z="-1772" isChaotic="true" />
	</region>
</list>
