=== DevMystogan/Datapack/gameserver/data/zones/zones.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   targetNamespace="http://l2j.org"
		   xmlns="http://l2j.org"
		   elementFormDefault="qualified">

	<xs:include schemaLocation="../xsd/common.xsd"/>

	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="zone" type="Zone" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="enabled" type="xs:boolean" default="true" />
		</xs:complexType>
	</xs:element>

	<xs:complexType name="Zone">
		<xs:sequence>
			<xs:element name="property" type="Property" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="point" type="Location" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="respawn" type="Respawn" maxOccurs="unbounded" minOccurs="0"/>
			<xs:element name="spawn" type="Spawn" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:positiveInteger" />
		<xs:attribute name="name" type="xs:normalizedString"/>
		<xs:attribute name="maxZ" type="xs:integer" use="required" />
		<xs:attribute name="minZ" type="xs:integer" use="required" />
		<xs:attribute name="form" type="ZoneForm" use="required"/>
		<xs:attribute name="type" type="xs:token" use="required"/>
		<xs:attribute name="radius" type="xs:positiveInteger" />
	</xs:complexType>

	<xs:complexType name="Property">
		<xs:attribute name="name" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:token">
					<xs:enumeration value="affectedLvlMin" />
					<xs:enumeration value="affectedRace" />
					<xs:enumeration value="allowStore" />
					<xs:enumeration value="castleId" />
					<xs:enumeration value="chance" />
					<xs:enumeration value="clanHallId" />
					<xs:enumeration value="dmgHPSec" />
					<xs:enumeration value="default_enabled" />
					<xs:enumeration value="domainId" />
					<xs:enumeration value="enterMsgId" />
					<xs:enumeration value="eventId" />
					<xs:enumeration value="fortId" />
					<xs:enumeration value="HpRegenBonus" />
					<xs:enumeration value="initialDelay" />
					<xs:enumeration value="instanceId" />
					<xs:enumeration value="instanceTemplate" />
					<xs:enumeration value="InvadeTime" />
					<xs:enumeration value="leaveMsgId" />
					<xs:enumeration value="maxDynamicSkillCount" />
					<xs:enumeration value="move_bonus" />
					<xs:enumeration value="MpRegenBonus" />
					<xs:enumeration value="NoBookmark" />
					<xs:enumeration value="NoItemDrop" />
					<xs:enumeration value="oustX" />
					<xs:enumeration value="oustY" />
					<xs:enumeration value="oustZ" />
					<xs:enumeration value="residenceId" />
					<xs:enumeration value="residenceZoneId" />
					<xs:enumeration value="restartAllowedTime" />
					<xs:enumeration value="restartTime" />
					<xs:enumeration value="reuse" />
					<xs:enumeration value="showDangerIcon" />
					<xs:enumeration value="skillIdLvl" />
					<xs:enumeration value="spawnMaxX" />
					<xs:enumeration value="spawnMaxY" />
					<xs:enumeration value="spawnMaxZ" />
					<xs:enumeration value="spawnMinX" />
					<xs:enumeration value="spawnMinY" />
					<xs:enumeration value="spawnMinZ" />
					<xs:enumeration value="spawnZ" />
					<xs:enumeration value="targetClass" />
					<xs:enumeration value="taxById" />
					<xs:enumeration value="territoryId" />
					<xs:enumeration value="townId" />
					<xs:enumeration value="mapId" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="value" type="xs:token" use="required" />
	</xs:complexType>

	<xs:complexType name="Spawn">
		<xs:complexContent>
			<xs:extension base="Location">
				<xs:attribute name="type" type="SpawnType" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:simpleType name="SpawnType">
		<xs:restriction base="xs:token">
			<xs:enumeration value="banish" />
			<xs:enumeration value="blueBanishPoint" />
			<xs:enumeration value="blueStartPoint" />
			<xs:enumeration value="challenger" />
			<xs:enumeration value="chaotic" />
			<xs:enumeration value="entrance" />
			<xs:enumeration value="other" />
			<xs:enumeration value="redBanishPoint" />
			<xs:enumeration value="redStartPoint" />
			<xs:enumeration value="spectatorSpawn" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="ZoneForm">
		<xs:restriction base="xs:token">
			<xs:enumeration value="Cube" />
			<xs:enumeration value="Cylinder" />
			<xs:enumeration value="Polygon" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="Respawn">
		<xs:attribute name="region" type="xs:token" use="required" />
		<xs:attribute name="race" type="Race" use="required" />
	</xs:complexType>

</xs:schema>

=== DevMystogan/Datapack/gameserver/data/zones/no_summon_friend.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://l2j.org" xsi:schemaLocation="http://l2j.org zones.xsd">
    <zone name="oracle_of_dusk_waitroom" type="org.l2j.gameserver.world.zone.type.NoSummonFriendZone" form="Polygon" minZ="-5383" maxZ="-4883">
        <point x="-82064" y="85608"/>
        <point x="-75832" y="85626"/>
        <point x="-75832" y="88068"/>
        <point x="-82099" y="88080"/>
    </zone>
    <zone name="oracle_of_dawn_waitroom" type="org.l2j.gameserver.world.zone.type.NoSummonFriendZone" form="Polygon" minZ="-5118" maxZ="-4618">
        <point x="-74529" y="110475"/>
        <point x="-75832" y="110476"/>
        <point x="-74524" y="113224"/>
        <point x="-80892" y="113211"/>
    </zone>
    <zone name="rift_between_worlds_waitroom" type="org.l2j.gameserver.world.zone.type.NoSummonFriendZone" form="Polygon" minZ="-6949" maxZ="-6449">
        <point x="-115608" y="-182374"/>
        <point x="-113976" y="-182380"/>
        <point x="-113990" y="-177851"/>
        <point x="-115606" y="-177858"/>
    </zone>
    <zone name="gm_prison" type="org.l2j.gameserver.world.zone.type.NoSummonFriendZone" form="Polygon" minZ="-2992" maxZ="-2792">
        <point x="-116390" y="-251581"/>
        <point x="-112756" y="-251617"/>
        <point x="-112720" y="-248199"/>
        <point x="-116354" y="-248217"/>
    </zone>
    <zone name="Hell_Bound_Island" type="org.l2j.gameserver.world.zone.type.NoSummonFriendZone" form="Polygon" minZ="-15000" maxZ="15000">
        <point x="-47730" y="228200"/>
        <point x="-48000" y="287833"/>
        <point x="48000" y="287833"/>
        <point x="48000" y="228200"/>
        <point x="-10026" y="228200"/>
    </zone>
    <zone name="boss_area_valakas" type="org.l2j.gameserver.world.zone.type.NoSummonFriendZone" form="Polygon" minZ="-3753" maxZ="32767">
        <point x="196710" y="-130845"/>
        <point x="228895" y="-130845"/>
        <point x="229126" y="-96162"/>
        <point x="196478" y="-98187"/>
    </zone>
    <zone name="boss_area_valakas2" type="org.l2j.gameserver.world.zone.type.NoSummonFriendZone" form="Polygon" minZ="-3753" maxZ="32767">
        <point x="183634" y="-115085"/>
        <point x="183634" y="-114885"/>
        <point x="184000" y="-115085"/>
        <point x="184000" y="-114885"/>
    </zone>
    <zone name="20_26_basetower_inner_01" type="org.l2j.gameserver.world.zone.type.NoSummonFriendZone" form="Polygon" minZ="-10736" maxZ="-5736">
        <point x="12080" y="274633"/>
        <point x="20523" y="274633"/>
        <point x="20553" y="284567"/>
        <point x="11947" y="284600"/>
    </zone>
    <zone name="19_26_tower_a_inner_01" type="org.l2j.gameserver.world.zone.type.NoSummonFriendZone" form="Polygon" minZ="-15364" maxZ="-6864">
        <point x="-23324" y="276243"/>
        <point x="-17912" y="276243"/>
        <point x="-17912" y="280871"/>
        <point x="-23324" y="280871"/>
    </zone>
    <zone name="19_26_tower_b_inner_01" type="org.l2j.gameserver.world.zone.type.NoSummonFriendZone" form="Polygon" minZ="-16148" maxZ="-4648">
        <point x="-15081" y="271397"/>
        <point x="-9858" y="271401"/>
        <point x="-9809" y="282115"/>
        <point x="-15085" y="282131"/>
    </zone>
    <zone name="20_24_beres_01" type="org.l2j.gameserver.world.zone.type.NoSummonFriendZone" form="Polygon" minZ="-10412" maxZ="-5112">
        <point x="11214" y="205578"/>
        <point x="20607" y="205578"/>
        <point x="20648" y="220271"/>
        <point x="11172" y="220271"/>
    </zone>
    <zone name="20_21_cruma_tower" type="org.l2j.gameserver.world.zone.type.NoSummonFriendZone" form="Polygon" minZ="-14581" maxZ="-4581">
        <point x="9951" y="106537"/>
        <point x="25483" y="106522"/>
        <point x="25456" y="121770"/>
        <point x="9991" y="121797"/>
    </zone>
    <zone name="14_25_kserth01" type="org.l2j.gameserver.world.zone.type.NoSummonFriendZone" form="Polygon" minZ="534" maxZ="4534">
        <point x="-185793" y="237221"/>
        <point x="-179675" y="239239"/>
        <point x="-182132" y="249166"/>
        <point x="-189240" y="247252"/>
    </zone>
    <zone name="13_24_undying01" type="org.l2j.gameserver.world.zone.type.NoSummonFriendZone" form="Polygon" minZ="4039" maxZ="5039">
        <point x="-215517" y="207306"/>
        <point x="-209939" y="207283"/>
        <point x="-209952" y="212489"/>
        <point x="-215511" y="212467"/>
    </zone>
    <zone name="14_24_undying02" type="org.l2j.gameserver.world.zone.type.NoSummonFriendZone" form="Polygon" minZ="-16246" maxZ="-6246">
        <point x="-188655" y="204450"/>
        <point x="-171766" y="204407"/>
        <point x="-171791" y="221459"/>
        <point x="-188592" y="221581"/>
    </zone>
    <zone name="12_24_destruction01" type="org.l2j.gameserver.world.zone.type.NoSummonFriendZone" form="Polygon" minZ="-13600" maxZ="-5600">
        <point x="-253983" y="204764"/>
        <point x="-237481" y="204721"/>
        <point x="-237521" y="221261"/>
        <point x="-253986" y="221221"/>
    </zone>
    <zone name="12_25_destruction02" type="org.l2j.gameserver.world.zone.type.NoSummonFriendZone" form="Polygon" minZ="3964" maxZ="5964">
        <point x="-253537" y="245296"/>
        <point x="-246362" y="245296"/>
        <point x="-246326" y="252369"/>
        <point x="-253537" y="252369"/>
    </zone>
    <zone name="14_23_annihilation01" type="org.l2j.gameserver.world.zone.type.NoSummonFriendZone" form="Polygon" minZ="-16312" maxZ="-5912">
        <point x="-193000" y="165212"/>
        <point x="-165004" y="165212"/>
        <point x="-165044" y="195382"/>
        <point x="-193000" y="195382"/>
    </zone>
    <zone name="13_23_annihilation02" type="org.l2j.gameserver.world.zone.type.NoSummonFriendZone" form="Polygon" minZ="-16384" maxZ="-5704">
        <point x="-221209" y="171933"/>
        <point x="-204834" y="171933"/>
        <point x="-204834" y="188552"/>
        <point x="-221209" y="188552"/>
    </zone>
    <zone name="14_23_annihilation03" type="org.l2j.gameserver.world.zone.type.NoSummonFriendZone" form="Polygon" minZ="-16096" maxZ="10228">
        <point x="-188401" y="139198"/>
        <point x="-171892" y="139242"/>
        <point x="-172090" y="155776"/>
        <point x="-188584" y="155747"/>
    </zone>
    <zone name="13_25_cleft01" type="org.l2j.gameserver.world.zone.type.NoSummonFriendZone" form="Polygon" minZ="-5412" maxZ="14587">
        <point x="-226831" y="234718"/>
        <point x="-201182" y="234791"/>
        <point x="-201182" y="255191"/>
        <point x="-226778" y="255249"/>
    </zone>
    <zone name="18_16_etc08_nocall" type="org.l2j.gameserver.world.zone.type.NoSummonFriendZone" form="Polygon" minZ="-2425" maxZ="-2225">
        <point x="-58571" y="64074"/>
        <point x="-56368" y="64071"/>
        <point x="-56370" y="61896"/>
        <point x="-58565" y="61904"/>
    </zone>
    <zone name="25_15_godard15_nocall" type="org.l2j.gameserver.world.zone.type.NoSummonFriendZone" form="Polygon" minZ="-8800" maxZ="200">
        <point x="164226" y="-94258"/>
        <point x="171998" y="-94378"/>
        <point x="171845" y="-84191"/>
        <point x="164030" y="-83790"/>
    </zone>
    <zone name="25_15_godard14_nocall" type="org.l2j.gameserver.world.zone.type.NoSummonFriendZone" form="Polygon" minZ="-8800" maxZ="200">
        <point x="176475" y="-90312"/>
        <point x="192224" y="-90260"/>
        <point x="192236" y="-84568"/>
        <point x="180669" y="-84640"/>
        <point x="180606" y="-82852"/>
        <point x="176498" y="-82757"/>
    </zone>
    <zone name="25_15_godard18_nocall" type="org.l2j.gameserver.world.zone.type.NoSummonFriendZone" form="Polygon" minZ="-7318" maxZ="-6718">
        <point x="172063" y="-90095"/>
        <point x="176460" y="-90057"/>
        <point x="176460" y="-74019"/>
        <point x="172089" y="-74076"/>
    </zone>
    <zone name="Tower_of_Insolence_Baium_nocall" type="org.l2j.gameserver.world.zone.type.NoSummonFriendZone" form="Polygon" minZ="8773" maxZ="32767">
        <point x="102382" y="2297"/>
        <point x="100118" y="30085"/>
        <point x="126188" y="29775"/>
        <point x="127178" y="3979"/>
    </zone>

    <!-- Classic Monster Race Track Arena -->
    <zone name="Monster_Race_Arena_NoCall" type="org.l2j.gameserver.world.zone.type.NoSummonFriendZone" form="Polygon" minZ="-3800" maxZ="-3550">
        <point x="13081" y="183060"/>
        <point x="13302" y="183285"/>
        <point x="13300" y="184089"/>
        <point x="13086" y="184308"/>
        <point x="11993" y="184308"/>
        <point x="11774" y="184091"/>
        <point x="11773" y="183287"/>
        <point x="11994" y="183055"/>
    </zone>
</list>
