=== DevMystogan/Datapack/gameserver/data/cubics.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT list (cubic)*>

	<!ELEMENT cubic (skill|op_cond)*>
	<!ATTLIST cubic
		id CDATA #REQUIRED
		level CDATA #REQUIRED
		slot CDATA #IMPLIED
		duration CDATA #REQUIRED
		delay CDATA #REQUIRED
		max_count CDATA #IMPLIED
		use_up CDATA #IMPLIED
		power CDATA #IMPLIED
		target_type CDATA #IMPLIED>

		<!ELEMENT skill (chance)*>
		<!ATTLIST skill
			chance CDATA #IMPLIED
			id CDATA #REQUIRED
			level CDATA #REQUIRED
			action_type CDATA #REQUIRED
			can_attack_door CDATA #REQUIRED
			use_chance CDATA #IMPLIED>

			<!ELEMENT chance (#PCDATA)>
			<!ATTLIST chance
				min_hp_percent CDATA #REQUIRED
				max_hp_percent CDATA #REQUIRED
				value CDATA #REQUIRED>

		<!ELEMENT op_cond (#PCDATA)>
		<!ATTLIST op_cond
			type CDATA #REQUIRED
			hp_percent CDATA #REQUIRED
			hp CDATA #REQUIRED>

=== DevMystogan/Datapack/gameserver/data/cubics.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "cubics.dtd">
<!--Created by VISTALL-->
<!--
Инструкция:

cubic id="1" level="1" delay="10"
id и level используется для нужной индефикации кубика
delay - тик кубика

У каждого скила есть групы скилов skills
chance="100" - шанс для вхождения в групу, подальшеии групы не обрабатыватся

Скилы skill id="4049" level="1"  для поиска нужного скила
action_type - тип действия
 - ATTACK - аттака
 - DEBUFF - дебафф
 - HEAL - хил один из пати у кого ХП ниже 100%
 - CANCEL - кенсел дебафов
chance - шанс прохождения скила
can_attack_door - может ли кубик бить дверь
-->
<list>
	<!--Storm Cubics-->
	<cubic id="1" level="1" duration="900" delay="10" max_count="30" use_up="INCREASE_DELAY" power="282.0" target_type="TARGET">
		<op_cond type="GREATER" hp_percent="33" hp="1000"/>
		<skill chance="100" id="4049" level="1" action_type="ATTACK" use_chance="12" can_attack_door="true"/>  <!--Cubic Drain-->
	</cubic>
	<cubic id="1" level="2" duration="900" delay="10" max_count="30" use_up="INCREASE_DELAY" power="434.0" target_type="TARGET">
		<op_cond type="GREATER" hp_percent="33" hp="1000"/>
		<skill chance="100" id="4049" level="2" action_type="ATTACK" use_chance="12" can_attack_door="true"/>  <!--Cubic Drain-->
	</cubic>
	<cubic id="1" level="3" duration="900" delay="10" max_count="30" use_up="INCREASE_DELAY" power="677.0" target_type="TARGET">
		<op_cond type="GREATER" hp_percent="33" hp="1000"/>
		<skill chance="100" id="4049" level="3" action_type="ATTACK" use_chance="12" can_attack_door="true"/>  <!--Cubic Drain-->
	</cubic>
	<cubic id="1" level="4" duration="900" delay="10" max_count="30" use_up="INCREASE_DELAY" power="919.0" target_type="TARGET">
		<op_cond type="GREATER" hp_percent="33" hp="1000"/>
		<skill chance="100" id="4049" level="4" action_type="ATTACK" use_chance="12" can_attack_door="true"/>  <!--Cubic Drain-->
	</cubic>
	<cubic id="1" level="5" duration="900" delay="10" max_count="30" use_up="INCREASE_DELAY" power="1141.0" target_type="TARGET">
		<op_cond type="GREATER" hp_percent="33" hp="1000"/>
		<skill chance="100" id="4049" level="5" action_type="ATTACK" use_chance="12" can_attack_door="true"/>  <!--Cubic Drain-->
	</cubic>
	<cubic id="1" level="6" duration="900" delay="10" max_count="30" use_up="INCREASE_DELAY" power="1394.0" target_type="TARGET">
		<op_cond type="GREATER" hp_percent="33" hp="1000"/>
		<skill chance="100" id="4049" level="6" action_type="ATTACK" use_chance="12" can_attack_door="true"/>  <!--Cubic Drain-->
	</cubic>
	<cubic id="1" level="7" duration="900" delay="10" max_count="30" use_up="INCREASE_DELAY" power="1673.0" target_type="TARGET">
		<op_cond type="GREATER" hp_percent="33" hp="1000"/>
		<skill chance="100" id="4049" level="7" action_type="ATTACK" use_chance="12" can_attack_door="true"/>  <!--Cubic Drain-->
	</cubic>
	<cubic id="1" level="8" duration="900" delay="10" max_count="30" use_up="INCREASE_DELAY" power="1975.0" target_type="TARGET">
		<op_cond type="GREATER" hp_percent="33" hp="1000"/>
		<skill chance="100" id="4049" level="8" action_type="ATTACK" use_chance="12" can_attack_door="true"/>  <!--Cubic Drain-->
	</cubic>
	<!--Vampiric Cubics-->
	<cubic id="2" level="1" duration="900" delay="15" max_count="20" use_up="INCREASE_DELAY" power="351.0" target_type="TARGET">
		<op_cond type="GREATER" hp_percent="33" hp="1000"/>
		<skill chance="100" id="4050" level="1" action_type="ATTACK" use_chance="8" can_attack_door="false"/>  <!--Cubic Drain-->
	</cubic>
	<cubic id="2" level="2" duration="900" delay="15" max_count="20" use_up="INCREASE_DELAY" power="531.0" target_type="TARGET">
		<op_cond type="GREATER" hp_percent="33" hp="1000"/>
		<skill chance="100" id="4050" level="2" action_type="ATTACK" use_chance="8" can_attack_door="false"/>  <!--Cubic Drain-->
	</cubic>
	<cubic id="2" level="3" duration="900" delay="15" max_count="20" use_up="INCREASE_DELAY" power="773.0" target_type="TARGET">
		<op_cond type="GREATER" hp_percent="33" hp="1000"/>
		<skill chance="100" id="4050" level="3" action_type="ATTACK" use_chance="8" can_attack_door="false"/>  <!--Cubic Drain-->
	</cubic>
	<cubic id="2" level="4" duration="900" delay="15" max_count="20" use_up="INCREASE_DELAY" power="1026.0" target_type="TARGET">
		<op_cond type="GREATER" hp_percent="33" hp="1000"/>
		<skill chance="100" id="4050" level="4" action_type="ATTACK" use_chance="8" can_attack_door="false"/>  <!--Cubic Drain-->
	</cubic>
	<cubic id="2" level="5" duration="900" delay="15" max_count="20" use_up="INCREASE_DELAY" power="1264.0" target_type="TARGET">
		<op_cond type="GREATER" hp_percent="33" hp="1000"/>
		<skill chance="100" id="4050" level="5" action_type="ATTACK" use_chance="8" can_attack_door="false"/>  <!--Cubic Drain-->
	</cubic>
	<cubic id="2" level="6" duration="900" delay="15" max_count="20" use_up="INCREASE_DELAY" power="1530.0" target_type="TARGET">
		<op_cond type="GREATER" hp_percent="33" hp="1000"/>
		<skill chance="100" id="4050" level="6" action_type="ATTACK" use_chance="8" can_attack_door="false"/>  <!--Cubic Drain-->
	</cubic>
	<cubic id="2" level="7" duration="900" delay="15" max_count="20" use_up="INCREASE_DELAY" power="1822.0" target_type="TARGET">
		<op_cond type="GREATER" hp_percent="33" hp="1000"/>
		<skill chance="100" id="4050" level="7" action_type="ATTACK" use_chance="8" can_attack_door="false"/>  <!--Cubic Drain-->
	</cubic>
	<!--Life Cubics-->
	<cubic id="3" level="1" duration="900" delay="13" max_count="20" use_up="INCREASE_DELAY" power="0" target_type="HEAL">
		<skill chance="100" id="4051" level="1" action_type="HEAL" can_attack_door="false">  <!--Cubic Heal-->
			<chance min_hp_percent="0" max_hp_percent="30" value="53"/>
			<chance min_hp_percent="31" max_hp_percent="60" value="30"/>
			<chance min_hp_percent="61" max_hp_percent="90" value="13"/>
		</skill>
	</cubic>
	<cubic id="3" level="2" duration="900" delay="13" max_count="20" use_up="INCREASE_DELAY" power="0" target_type="HEAL">
		<skill chance="100" id="4051" level="2" action_type="HEAL" can_attack_door="false">  <!--Cubic Heal-->
			<chance min_hp_percent="0" max_hp_percent="30" value="53"/>
			<chance min_hp_percent="31" max_hp_percent="60" value="30"/>
			<chance min_hp_percent="61" max_hp_percent="90" value="13"/>
		</skill>
	</cubic>
	<cubic id="3" level="3" duration="900" delay="13" max_count="20" use_up="INCREASE_DELAY" power="0" target_type="HEAL">
		<skill chance="100" id="4051" level="3" action_type="HEAL" can_attack_door="false">  <!--Cubic Heal-->
			<chance min_hp_percent="0" max_hp_percent="30" value="53"/>
			<chance min_hp_percent="31" max_hp_percent="60" value="30"/>
			<chance min_hp_percent="61" max_hp_percent="90" value="13"/>
		</skill>
	</cubic>
	<cubic id="3" level="4" duration="900" delay="13" max_count="20" use_up="INCREASE_DELAY" power="0" target_type="HEAL">
		<skill chance="100" id="4051" level="4" action_type="HEAL" can_attack_door="false">  <!--Cubic Heal-->
			<chance min_hp_percent="0" max_hp_percent="30" value="53"/>
			<chance min_hp_percent="31" max_hp_percent="60" value="30"/>
			<chance min_hp_percent="61" max_hp_percent="90" value="13"/>
		</skill>
	</cubic>
	<cubic id="3" level="5" duration="900" delay="13" max_count="20" use_up="INCREASE_DELAY" power="0" target_type="HEAL">
		<skill chance="100" id="4051" level="5" action_type="HEAL" can_attack_door="false">  <!--Cubic Heal-->
			<chance min_hp_percent="0" max_hp_percent="30" value="53"/>
			<chance min_hp_percent="31" max_hp_percent="60" value="30"/>
			<chance min_hp_percent="61" max_hp_percent="90" value="13"/>
		</skill>
	</cubic>
	<cubic id="3" level="6" duration="900" delay="13" max_count="20" use_up="INCREASE_DELAY" power="0" target_type="HEAL">
		<skill chance="100" id="4051" level="6" action_type="HEAL" can_attack_door="false">  <!--Cubic Heal-->
			<chance min_hp_percent="0" max_hp_percent="30" value="53"/>
			<chance min_hp_percent="31" max_hp_percent="60" value="30"/>
			<chance min_hp_percent="61" max_hp_percent="90" value="13"/>
		</skill>
	</cubic>
	<cubic id="3" level="7" duration="900" delay="13" max_count="20" use_up="INCREASE_DELAY" power="0" target_type="HEAL">
		<skill chance="100" id="4051" level="7" action_type="HEAL" can_attack_door="false">  <!--Cubic Heal-->
			<chance min_hp_percent="0" max_hp_percent="30" value="53"/>
			<chance min_hp_percent="31" max_hp_percent="60" value="30"/>
			<chance min_hp_percent="61" max_hp_percent="90" value="13"/>
		</skill>
	</cubic>
	<!--Viper Cubics-->
	<cubic id="4" level="1" duration="900" delay="20" max_count="15" use_up="INCREASE_DELAY" power="531.0" target_type="TARGET">
		<op_cond type="GREATER" hp_percent="33" hp="1000"/>
		<skill chance="100" id="4052" level="1" action_type="DEBUFF" use_chance="20" can_attack_door="false"/>  <!--Poison-->
	</cubic>
	<cubic id="4" level="2" duration="900" delay="20" max_count="15" use_up="INCREASE_DELAY" power="773.0" target_type="TARGET">
		<op_cond type="GREATER" hp_percent="33" hp="1000"/>
		<skill chance="100" id="4052" level="2" action_type="DEBUFF" use_chance="20" can_attack_door="false"/>  <!--Poison-->
	</cubic>
	<cubic id="4" level="3" duration="900" delay="20" max_count="15" use_up="INCREASE_DELAY" power="1026.0" target_type="TARGET">
		<op_cond type="GREATER" hp_percent="33" hp="1000"/>
		<skill chance="100" id="4052" level="3" action_type="DEBUFF" use_chance="20" can_attack_door="false"/>  <!--Poison-->
	</cubic>
	<cubic id="4" level="4" duration="900" delay="20" max_count="15" use_up="INCREASE_DELAY" power="1264.0" target_type="TARGET">
		<op_cond type="GREATER" hp_percent="33" hp="1000"/>
		<skill chance="100" id="4052" level="4" action_type="DEBUFF" use_chance="20" can_attack_door="false"/>  <!--Poison-->
	</cubic>
	<cubic id="4" level="5" duration="900" delay="20" max_count="15" use_up="INCREASE_DELAY" power="1530.0" target_type="TARGET">
		<op_cond type="GREATER" hp_percent="33" hp="1000"/>
